### ISSUE TITLE
[MASSEMBLY-889] Maven assembly not able to handle large capacity .tar.gz packaging

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#1099]
**[Sriram Kotni](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srkotni)** opened **[MASSEMBLY-889](https://issues.apache.org/jira/browse/MASSEMBLY-889?redirect=false)** and commented

We are using Maven assembly to tar.gz file size of 2.5 gb is not able to handle. Because of this we are not able support multi language Knowledge Base support. There is a big impact for our business. 

Any suggestions and alternate solutions are appreciated.

 

Thanks,

Sriram

---

**Affects:** 2.4

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

What does `is not able to handle`..mean..? Furthermore an example pom with descriptor and of course log files would be great (with the appropriate error messages)..apart from that I've already created files with 10GiB+ size with maven-assembly-plugin ? Furthermore which Maven versions are you using and which JDK version are you running? Is this happening on plain command line or inside Jenkins like environments?

**Comment by jira-importer** [comment]
**[Sriram Kotni](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srkotni)** commented

Assembly i.e. creating the tat.gz) is failing if the tar file size is 2.5 gb.
Sriram

Sent from my Samsung Galaxy smartphone.

-------- Original message --------
From: "Karl Heinz Marbaise (JIRA)" <jira@apache.org>
Date: 6/2/18 2:16 AM (GMT-08:00)
To: "Sriram Kotni (srkotni)" <srkotni@cisco.com>
Subject: [jira] [Commented] (MASSEMBLY-889) Maven assembly not able to handle large capacity .tar.gz packaging

    [ https://issues.apache.org/jira/browse/MASSEMBLY-889?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=16498948#comment-16498948 ]

Karl Heinz Marbaise commented on MASSEMBLY-889:

---

What does `is not able to handle`..mean..? Furthermore an example pom with descriptor and of course log files would be great (with the appropriate error messages)..apart from that I've already created files with 10GiB+ size with maven-assembly-plugin ? Furthermore which Maven versions are you using and which JDK version are you running? Is this happening on plain command line or inside Jenkins like environments?

---

This message was sent by Atlassian JIRA
(v7.6.3#76005)

**Comment by jira-importer** [comment]
**[Sriram Kotni](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srkotni)** commented

I will send details in a bit.
Thanks
Sriram

Sent from my Samsung Galaxy smartphone.

-------- Original message --------
From: "Karl Heinz Marbaise (JIRA)" <jira@apache.org>
Date: 6/2/18 2:16 AM (GMT-08:00)
To: "Sriram Kotni (srkotni)" <srkotni@cisco.com>
Subject: [jira] [Commented] (MASSEMBLY-889) Maven assembly not able to handle large capacity .tar.gz packaging

    [ https://issues.apache.org/jira/browse/MASSEMBLY-889?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=16498948#comment-16498948 ]

Karl Heinz Marbaise commented on MASSEMBLY-889:

---

What does `is not able to handle`..mean..? Furthermore an example pom with descriptor and of course log files would be great (with the appropriate error messages)..apart from that I've already created files with 10GiB+ size with maven-assembly-plugin ? Furthermore which Maven versions are you using and which JDK version are you running? Is this happening on plain command line or inside Jenkins like environments?

---

This message was sent by Atlassian JIRA
(v7.6.3#76005)

**Comment by jira-importer** [comment]
**[Sriram Kotni](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srkotni)** commented

Hi Karl,

I am using EMBEDDED maven in eclipse version 3.3.3/1.6.320160209-1444
And on Jenkins I am using Maven-3.3.1
JDB I used both 1.7 and 1.8

Environment is in Jenkins and also ecliplse:
Eclipse Java EE IDE for Web Developers.
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

My pom.xml:

\<?xml version="1.0" encoding="UTF-8"?>
\<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
\<modelVersion>4.0.0\</modelVersion>
\<groupId>it.cits.ciscoworkforcecontentservices.kbconnectsdaas.jasperconnectkb\</groupId>
\<artifactId>tomcat7\</artifactId>
\<packaging>pom\</packaging>
\<version>1.0.0-SNAPSHOT\</version>
\<name>tomcat7 Maven Webapp\</name>
\<modules>
\<module>ConnectKBM\</module>
\<module>ConnectKBR\</module>
\</modules>
\<build>
		\<plugins>
			\<plugin>
				\<groupId>org.apache.maven.plugins\</groupId>
				\<artifactId>maven-assembly-plugin\</artifactId>
				\<version>2.4\</version>
				\<executions>
					\<execution>
						\<id>package-tar-gz\</id>
						\<phase>package\</phase>
						\<goals>
							\<goal>single\</goal>
						\</goals>
					\</execution>
				\</executions>
				\<configuration>
					\<appendAssemblyId>false\</appendAssemblyId>
					\<descriptors>
						\<descriptor>assembly.xml\</descriptor>
					\</descriptors>
				\</configuration>
			\</plugin>
		\</plugins>
	\</build>
\</project>

And my assembly.xml

\<?xml version="1.0" encoding="UTF-8"?>
\<assembly>
\<id>${project.version}\</id>
\<formats>
\<format>tar.gz\</format>
\</formats>
\<files>
\<file>
\<source>pom.xml\</source>
\<outputDirectory>/package\</outputDirectory>
\</file>
\</files>
\<includeBaseDirectory>false\</includeBaseDirectory>
\<fileSets>
\<fileSet>
	\<directory>${project.build.directory}/../package\</directory>
		\<outputDirectory>/\</outputDirectory>
\</fileSet>
\</fileSets>
\</assembly>

Some debug information:

May be this message will give some clue: “DEBUG] Cannot find ArtifactResolver with hint: project-cache-aware”

---

[INFO] Reading assembly descriptor: assembly.xml
[DEBUG] Before assembly is interpolated:

\<?xml version="1.0" encoding="UTF-8"?>

\<assembly xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2 http://maven.apache.org/xsd/assembly-1.1.2.xsd"
xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
\<id>${project.version}\</id>
\<formats>
\<format>tar.gz\</format>
\</formats>
\<includeBaseDirectory>false\</includeBaseDirectory>
\<fileSets>
\<fileSet>
\<outputDirectory>/\</outputDirectory>
\<directory>${project.build.directory}/../package\</directory>
\</fileSet>
\</fileSets>
\</assembly>

[DEBUG] After assembly is interpolated:

\<?xml version="1.0" encoding="UTF-8"?>

\<assembly xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2 http://maven.apache.org/xsd/assembly-1.1.2.xsd"
xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
\<id>1.0.0-SNAPSHOT\</id>
\<formats>
\<format>tar.gz\</format>
\</formats>
\<includeBaseDirectory>false\</includeBaseDirectory>
\<fileSets>
\<fileSet>
\<outputDirectory>/\</outputDirectory>
\<directory>target/../package\</directory>
\</fileSet>
\</fileSets>
\</assembly>

[DEBUG] All known ContainerDescriptorHandler components: [plexus, file-aggregator, metaInf-services, metaInf-spring]
[DEBUG] Cannot find ArtifactResolver with hint: project-cache-aware
org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
role: org.apache.maven.artifact.resolver.ArtifactResolver
roleHint: project-cache-aware
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:243)

Sriram Kotni
srkotni@cisco.com
Cisco Systems, Inc.
3003 Bunker Hill Lane
SANTA CLARA 95054
United States

Think before you print.
This email may contain confidential and privileged material for the sole use of the intended recipient. Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender by reply email and delete all copies of this message.
Please click here for Company Registration Information.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

You should try with the most recent version of Maven and this plugin. We do not provide support for old versions.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Please try the most recent version cause there had been large improvements afterwards for large files....

**Comment by jira-importer** [comment]
**[Sriram Kotni](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srkotni)** commented

I will try latest version and see if it helps.

Thanks,
--Sriram

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

I saw feedback from OOZIE-3120 that with 3.1 they have no problem with archive size.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Failed to provide reasonable evidence.
