### ISSUE TITLE
[MASSEMBLY-7] descriptorId not set via commandline switch

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#252]
**[Andrew Moore](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amm)** opened **[MASSEMBLY-7](https://issues.apache.org/jira/browse/MASSEMBLY-7?redirect=false)** and commented

When calling assembly:assembly, the assembly descriptorId does not
appear to be set when specifying maven.assembly.descriptorId via a
command line switch [1].

org.apache.maven.BuildFailureException: You must specify descriptor or
descriptorId

If the descriptorId is set in the project POM [2] it works as expected [3].

Listing 1:

$ m2 -X -Dmaven.assembly.descriptorId=src clean:clean assembly:assembly
+ Error stacktraces are turned on.
  [DEBUG] Building Maven user-level plugin registry from:
  '/home/amm/.m2/plugin-registry.xml'
  [DEBUG] Building Maven global-level plugin registry from:
  '/opt/maven/conf/plugin-registry.xml'
  [INFO] Scanning for projects...
  [INFO] Searching repository for plugin with prefix: 'clean'.
  [DEBUG] maven-clean-plugin: resolved to version 2.0 from repository central
  [DEBUG] Retrieving parent-POM from the repository for project:
  null:maven-clean-plugin:maven-plugin:2.0
  [DEBUG] maven-assembly-plugin: resolved to version 2.0 from repository
  central
  [DEBUG] Retrieving parent-POM from the repository for project:
  null:maven-assembly-plugin:maven-plugin:2.0
  [INFO]

---

[INFO] Building Maven Quick Start Archetype
[INFO]    task-segment: [clean:clean]
[INFO]

---

[DEBUG] org.apache.maven.plugins:maven-clean-plugin:maven-plugin:2.0
(selected for runtime)
[DEBUG] Configuring mojo
'org.apache.maven.plugins:maven-clean-plugin:2.0:clean' -->
[DEBUG]   (f) directory = /secure/home/amm/prj/bt3/distra/test/target
[DEBUG]   (f) outputDirectory =
/secure/home/amm/prj/bt3/distra/test/target/classes
[DEBUG]   (f) testOutputDirectory =
/secure/home/amm/prj/bt3/distra/test/target/test-classes
[DEBUG]   - end configuration --
[INFO] [clean:clean]
[INFO] Deleting directory /secure/home/amm/prj/bt3/distra/test/target
[INFO]

---

[INFO] Building Maven Quick Start Archetype
[INFO]    task-segment: [assembly:assembly] (aggregator-style)
[INFO]

---

[INFO] Preparing assembly:assembly
[INFO]

---

[INFO] Building Maven Quick Start Archetype
[INFO]

---

[DEBUG] maven-resources-plugin: resolved to version 2.0 from repository
central
[DEBUG] Retrieving parent-POM from the repository for project:
null:maven-resources-plugin:maven-plugin:2.0
[DEBUG] maven-compiler-plugin: resolved to version 2.0 from repository
central
[DEBUG] Retrieving parent-POM from the repository for project:
null:maven-compiler-plugin:maven-plugin:2.0
[DEBUG] maven-surefire-plugin: resolved to version 2.0-beta-1 from
repository central
[DEBUG] Retrieving parent-POM from the repository for project:
null:maven-surefire-plugin:maven-plugin:2.0-beta-1
[DEBUG] maven-jar-plugin: resolved to version 2.0 from repository central
[DEBUG] Retrieving parent-POM from the repository for project:
null:maven-jar-plugin:maven-plugin:2.0
[DEBUG] org.apache.maven.plugins:maven-resources-plugin:maven-plugin:2.0
(selected for runtime)
[DEBUG]   commons-io:commons-io:jar:1.0 (selected for runtime)
[DEBUG]     junit:junit:jar:3.8.1 (selected for runtime)
[DEBUG] Configuring mojo
'org.apache.maven.plugins:maven-resources-plugin:2.0:resources' -->
[DEBUG]   (f) filters = []
[DEBUG]   (f) outputDirectory =
/secure/home/amm/prj/bt3/distra/test/target/classes
[DEBUG]   (f) project = org.apache.maven.project.MavenProject@8f7ffc4a
[DEBUG]   (f) resources = [org.apache.maven.model.Resource@175078b]
[DEBUG]   - end configuration --
[INFO] [resources:resources]
[INFO] Using default encoding to copy filtered resources.
[DEBUG] com.distra.maven:test:jar:1.0-SNAPSHOT (selected for null)
[DEBUG] org.apache.maven.plugins:maven-compiler-plugin:maven-plugin:2.0
(selected for runtime)
[DEBUG]   org.codehaus.plexus:plexus-compiler-api:jar:1.5.1 (selected
for runtime)
[DEBUG]   org.codehaus.plexus:plexus-compiler-manager:jar:1.5.1
(selected for runtime)
[DEBUG]     org.codehaus.plexus:plexus-compiler-api:jar:1.5.1 (selected
for runtime)
[DEBUG]   org.codehaus.plexus:plexus-compiler-javac:jar:1.5.1 (selected
for runtime)
[DEBUG]     org.codehaus.plexus:plexus-compiler-api:jar:1.5.1 (selected
for runtime)
[DEBUG] Configuring mojo
'org.apache.maven.plugins:maven-compiler-plugin:2.0:compile' -->
[DEBUG]   (f) basedir = /secure/home/amm/prj/bt3/distra/test
[DEBUG]   (f) buildDirectory = /secure/home/amm/prj/bt3/distra/test/target
[DEBUG]   (f) classpathElements =
[/secure/home/amm/prj/bt3/distra/test/target/classes]
[DEBUG]   (f) compileSourceRoots =
[/secure/home/amm/prj/bt3/distra/test/src/main/java]
[DEBUG]   (f) compilerId = javac
[DEBUG]   (f) debug = true
[DEBUG]   (f) fork = false
[DEBUG]   (f) optimize = false
[DEBUG]   (f) outputDirectory =
/secure/home/amm/prj/bt3/distra/test/target/classes
[DEBUG]   (f) outputFileName = test-1.0-SNAPSHOT
[DEBUG]   (f) projectArtifact = com.distra.maven:test:jar:1.0-SNAPSHOT
[DEBUG]   (f) staleMillis = 0
[DEBUG]   (f) verbose = false
[DEBUG]   - end configuration --
[INFO] [compiler:compile]
[DEBUG] Using compiler 'javac'.
[DEBUG] Source directories:
[/secure/home/amm/prj/bt3/distra/test/src/main/java]
[DEBUG] Classpath: [/secure/home/amm/prj/bt3/distra/test/target/classes]
[DEBUG] Output directory:
/secure/home/amm/prj/bt3/distra/test/target/classes
[DEBUG] Classpath:
[DEBUG]  /secure/home/amm/prj/bt3/distra/test/target/classes
[DEBUG] Source roots:
[DEBUG]  /secure/home/amm/prj/bt3/distra/test/src/main/java
Compiling 1 source file to
/secure/home/amm/prj/bt3/distra/test/target/classes
[DEBUG] Configuring mojo
'org.apache.maven.plugins:maven-resources-plugin:2.0:testResources' -->
[DEBUG]   (f) filters = []
[DEBUG]   (f) outputDirectory =
/secure/home/amm/prj/bt3/distra/test/target/test-classes
[DEBUG]   (f) project = org.apache.maven.project.MavenProject@8f7ffc4a
[DEBUG]   (f) resources = [org.apache.maven.model.Resource@7cbde6]
[DEBUG]   - end configuration --
[INFO] [resources:testResources]
[INFO] Using default encoding to copy filtered resources.
[DEBUG] com.distra.maven:test:jar:1.0-SNAPSHOT (selected for null)
[DEBUG]   junit:junit:jar:3.8.1 (selected for test)
[DEBUG] Configuring mojo
'org.apache.maven.plugins:maven-compiler-plugin:2.0:testCompile' -->
[DEBUG]   (f) basedir = /secure/home/amm/prj/bt3/distra/test
[DEBUG]   (f) buildDirectory = /secure/home/amm/prj/bt3/distra/test/target
[DEBUG]   (f) classpathElements =
[/secure/home/amm/prj/bt3/distra/test/target/classes,
/home/amm/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar]
[DEBUG]   (f) compileSourceRoots =
[/secure/home/amm/prj/bt3/distra/test/src/test/java]
[DEBUG]   (f) compilerId = javac
[DEBUG]   (f) debug = true
[DEBUG]   (f) fork = false
[DEBUG]   (f) optimize = false
[DEBUG]   (f) outputDirectory =
/secure/home/amm/prj/bt3/distra/test/target/test-classes
[DEBUG]   (f) outputFileName = test-1.0-SNAPSHOT
[DEBUG]   (f) staleMillis = 0
[DEBUG]   (f) verbose = false
[DEBUG]   - end configuration --
[INFO] [compiler:testCompile]
[DEBUG] Using compiler 'javac'.
[DEBUG] Source directories:
[/secure/home/amm/prj/bt3/distra/test/src/test/java]
[DEBUG] Classpath: [/secure/home/amm/prj/bt3/distra/test/target/classes
/home/amm/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar]
[DEBUG] Output directory:
/secure/home/amm/prj/bt3/distra/test/target/test-classes
[DEBUG] Classpath:
[DEBUG]  /secure/home/amm/prj/bt3/distra/test/target/classes
[DEBUG]  /home/amm/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[DEBUG] Source roots:
[DEBUG]  /secure/home/amm/prj/bt3/distra/test/src/test/java
Compiling 1 source file to
/secure/home/amm/prj/bt3/distra/test/target/test-classes
[DEBUG] com.distra.maven:test:jar:1.0-SNAPSHOT (selected for null)
[DEBUG]   junit:junit:jar:3.8.1 (selected for test)
[DEBUG]
org.apache.maven.plugins:maven-surefire-plugin:maven-plugin:2.0-beta-1
(selected for runtime)
[DEBUG]   junit:junit:jar:3.8.1 (selected for runtime)
[DEBUG] Retrieving parent-POM from the repository for project:
null:surefire:jar:1.3
[DEBUG]   surefire:surefire:jar:1.3 (selected for runtime)
[DEBUG]     junit:junit:jar:3.8.1 (selected for runtime)
[DEBUG] Retrieving parent-POM from the repository for project:
null:surefire-booter:jar:1.3
[DEBUG]   surefire:surefire-booter:jar:1.3 (selected for runtime)
[DEBUG]     junit:junit:jar:3.8.1 (selected for runtime)
[DEBUG]     surefire:surefire:jar:1.3 (selected for runtime)
[DEBUG] Configuring mojo
'org.apache.maven.plugins:maven-surefire-plugin:2.0-beta-1:test' -->
[DEBUG]   (f) basedir = /secure/home/amm/prj/bt3/distra/test
[DEBUG]   (f) classesDirectory =
/secure/home/amm/prj/bt3/distra/test/target/classes
[DEBUG]   (f) classpathElements =
[/secure/home/amm/prj/bt3/distra/test/target/classes,
/home/amm/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar]
[DEBUG]   (f) localRepository = [local] -> file:///home/amm/.m2/repository
[DEBUG]   (f) pluginArtifacts = [junit:junit:jar:3.8.1,
surefire:surefire:jar:1.3, surefire:surefire-booter:jar:1.3,
org.apache.maven.wagon:wagon-provider-api:jar:1.0-alpha-4,
plexus:plexus-utils:jar:1.0.3,
org.apache.maven:maven-artifact-manager:jar:2.0-beta-1,
org.apache.maven:maven-model:jar:2.0-beta-1,
classworlds:classworlds:jar:1.1-alpha-2,
org.apache.maven:maven-repository-metadata:jar:2.0-beta-1,
plexus:plexus-container-default:jar:1.0-alpha-6,
org.apache.maven:maven-profile:jar:2.0-beta-1,
org.apache.maven:maven-plugin-api:jar:2.0-beta-1,
org.apache.maven:maven-project:jar:2.0-beta-1,
org.apache.maven:maven-artifact:jar:2.0-beta-1]
[DEBUG]   (f) reportsDirectory =
/secure/home/amm/prj/bt3/distra/test/target/surefire-reports
[DEBUG]   (f) testClassesDirectory =
/secure/home/amm/prj/bt3/distra/test/target/test-classes
[DEBUG]   - end configuration --
[INFO] [surefire:test]
[INFO] Setting reports dir:
/secure/home/amm/prj/bt3/distra/test/target/surefire-reports

---

T E S T S

---

[surefire] Running com.distra.maven.AppTest
[surefire] Tests run: 1, Failures: 0, Errors: 0, Time elapsed: 0.003 sec

Results :
[surefire] Tests run: 1, Failures: 0, Errors: 0

[DEBUG] org.apache.maven.plugins:maven-jar-plugin:maven-plugin:2.0
(selected for runtime)
[DEBUG] Retrieving parent-POM from the repository for project:
null:maven-archiver:jar:2.0
[DEBUG]   org.apache.maven:maven-archiver:jar:2.0 (selected for runtime)
[DEBUG]     org.codehaus.plexus:plexus-archiver:jar:1.0-alpha-3
(selected for runtime)
[DEBUG] Configuring mojo
'org.apache.maven.plugins:maven-jar-plugin:2.0:jar' -->
[DEBUG]   (f) basedir = /secure/home/amm/prj/bt3/distra/test/target
[DEBUG]   (f) finalName = test-1.0-SNAPSHOT
[DEBUG]   (f) outputDirectory =
/secure/home/amm/prj/bt3/distra/test/target/classes
[DEBUG]   (f) project = org.apache.maven.project.MavenProject@8f7ffc4a
[DEBUG]   - end configuration --
[INFO] [jar:jar]
[INFO] Building jar:
/secure/home/amm/prj/bt3/distra/test/target/test-1.0-SNAPSHOT.jar
[DEBUG] adding directory META-INF/
[DEBUG] adding entry META-INF/MANIFEST.MF
[DEBUG] adding directory com/
[DEBUG] adding directory com/distra/
[DEBUG] adding directory com/distra/maven/
[DEBUG] adding entry com/distra/maven/App.class
[DEBUG] adding directory META-INF/maven/
[DEBUG] adding directory META-INF/maven/com.distra.maven/
[DEBUG] adding directory META-INF/maven/com.distra.maven/test/
[DEBUG] adding entry META-INF/maven/com.distra.maven/test/pom.xml
[DEBUG] adding entry META-INF/maven/com.distra.maven/test/pom.properties
[DEBUG] com.distra.maven:test:jar:1.0-SNAPSHOT (selected for null)
[DEBUG]   junit:junit:jar:3.8.1 (selected for test)
[DEBUG] org.apache.maven.plugins:maven-assembly-plugin:maven-plugin:2.0
(selected for runtime)
[DEBUG]   org.codehaus.plexus:plexus-archiver:jar:1.0-alpha-3 (selected
for runtime)
[DEBUG] Configuring mojo
'org.apache.maven.plugins:maven-assembly-plugin:2.0:assembly' -->
[DEBUG]   (f) basedir = /secure/home/amm/prj/bt3/distra/test
[DEBUG]   (f) dependencies = [junit:junit:jar:3.8.1]
[DEBUG]   (f) finalName = test-1.0-SNAPSHOT
[DEBUG]   (f) includeSite = false
[DEBUG]   (f) outputDirectory = /secure/home/amm/prj/bt3/distra/test/target
[DEBUG]   (f) project = org.apache.maven.project.MavenProject@8f7ffc4a
[DEBUG]   (f) siteDirectory =
/secure/home/amm/prj/bt3/distra/test/target/site
[DEBUG]   (f) tempRoot =
/secure/home/amm/prj/bt3/distra/test/target/archive-tmp
[DEBUG]   (f) workDirectory =
/secure/home/amm/prj/bt3/distra/test/target/assembly/work
[DEBUG]   - end configuration --
[INFO] [assembly:assembly]
[INFO]

---

[ERROR] BUILD FAILURE
[INFO]

---

[INFO] You must specify descriptor or descriptorId
[INFO]

---

[DEBUG] Trace
org.apache.maven.BuildFailureException: You must specify descriptor or
descriptorId
at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:540)
at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:482)
at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:452)
at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:214)
at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:316)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at
org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at
org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoFailureException: You must
specify descriptor or descriptorId
at
org.apache.maven.plugin.assembly.AssemblyMojo.readAssembly(AssemblyMojo.java:223)
at
org.apache.maven.plugin.assembly.AssemblyMojo.execute(AssemblyMojo.java:144)
at
org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:399)
at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
... 16 more
[INFO]

---

[INFO] Total time: 5 seconds
[INFO] Finished at: Tue Oct 18 11:48:52 EST 2005
[INFO] Final Memory: 3M/9M
[INFO]

---

Listing 2:

...
\<build>
\<plugins>
\<plugin>
\<artifactId>maven-assembly-plugin\</artifactId>
\<version>2.0\</version>
\<configuration>
\<descriptorId>src\</descriptorId>
\</configuration>
\</plugin>
\</plugins>
\</build>
...

Listing 3:

$ m2 clean:clean assembly:assembly
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'clean'.
[INFO]

---

[INFO] Building Maven Quick Start Archetype
[INFO]    task-segment: [clean:clean]
[INFO]

---

[INFO] [clean:clean]
[INFO] Deleting directory /secure/home/amm/prj/bt3/distra/test/target
[INFO]

---

[INFO] Building Maven Quick Start Archetype
[INFO]    task-segment: [assembly:assembly] (aggregator-style)
[INFO]

---

[INFO] Preparing assembly:assembly
[INFO]

---

[INFO] Building Maven Quick Start Archetype
[INFO]

---

[INFO] [resources:resources]
[INFO] Using default encoding to copy filtered resources.
[INFO] [compiler:compile]
Compiling 1 source file to
/secure/home/amm/prj/bt3/distra/test/target/classes
[INFO] [resources:testResources]
[INFO] Using default encoding to copy filtered resources.
[INFO] [compiler:testCompile]
Compiling 1 source file to
/secure/home/amm/prj/bt3/distra/test/target/test-classes
[INFO] [surefire:test]
[INFO] Setting reports dir:
/secure/home/amm/prj/bt3/distra/test/target/surefire-reports

---

T E S T S

---

[surefire] Running com.distra.maven.AppTest
[surefire] Tests run: 1, Failures: 0, Errors: 0, Time elapsed: 0.004 sec

Results :
[surefire] Tests run: 1, Failures: 0, Errors: 0

[INFO] [jar:jar]
[INFO] Building jar:
/secure/home/amm/prj/bt3/distra/test/target/test-1.0-SNAPSHOT.jar
[INFO] [assembly:assembly]
[INFO] Building tar :
/secure/home/amm/prj/bt3/distra/test/target/test-1.0-SNAPSHOT-src.tar.gz
[INFO] Building tar :
/secure/home/amm/prj/bt3/distra/test/target/test-1.0-SNAPSHOT-src.tar.bz2
[INFO] Building zip:
/secure/home/amm/prj/bt3/distra/test/target/test-1.0-SNAPSHOT-src.zip
[INFO]

---

[INFO] BUILD SUCCESSFUL
[INFO]

---

[INFO] Total time: 6 seconds
[INFO] Finished at: Tue Oct 18 11:38:10 EST 2005
[INFO] Final Memory: 15M/27M
[INFO]

---

---

**Attachments:**
- [MNG-1229-maven-assembly-plugin.patch](https://issues.apache.org/jira/secure/attachment/12714025/MNG-1229-maven-assembly-plugin.patch) (_4.13 kB_)

**Comment by jira-importer** [comment]
**[Johnny R. Ruiz III](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jruiz)** commented

$ m2 -X -Dmaven.assembly.descriptorId=src clean:clean assembly:assembly

I think you are using the wrong parameter for setting the descriptorId.   Instead of using your command above, you should use:

$ m2 -X  -DdescriptorId=src clean:clean assembly:assembly

you could also set -Ddescriptor=<descriptor.file>

Try it out! Hope it works.

**Comment by jira-importer** [comment]
**[Andrew Moore](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amm)** commented

m2 -DdescriptorId=src assembly:assembly

works as expected.

The documentation at <http://maven.apache.org/maven2/plugins/maven-assembly-plugin/howto.html> may need to be updated as it still refers to -Dmaven.assembly.descriptorId.

Cheers,
...andrew

**Comment by jira-importer** [comment]
**[Johnny R. Ruiz III](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jruiz)** commented

- I'm going to update the howto.apt.
- There is also need to change the expression value of  "outputDirectory" from   "${project.build.directory}/site" to "${project.reporting.outputDirectory}".

**Comment by jira-importer** [comment]
**[Johnny R. Ruiz III](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jruiz)** commented

I updated the Howto documentation.
- changed " -Dmaven.assembly.descriptorId"  -->  "-DdescriptorId"
- changed "-Dmaven.assembly.descriptor"  -->  "-Ddescriptor"
- updated the howto for assembly:goal

Please apply this patch.   Thanks a lot.
