### ISSUE TITLE
[MASSEMBLY-15] AssemblyMojo uses unknown methods in plexus-utils

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#259]
**[Achim Huegen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ahuegen)** opened **[MASSEMBLY-15](https://issues.apache.org/jira/browse/MASSEMBLY-15?redirect=false)** and commented

Class AssemblyMojo calls method org.codehaus.plexus.util.FileUtils.getDefaultExcludesAsList()
that is not present in plexus-utils 1.0.4 which is the latest version available in the ibiblio repository.
This results in a NoSuchMethodError exception when calling m2 assembly:assembly :

Exception in thread "main" java.lang.NoSuchMethodError: org.codehaus.plexus.util.FileUtils.getDefaultExcludesAsList()Ljava/util/List;
at org.apache.maven.plugin.assembly.AssemblyMojo.processFileSets(AssemblyMojo.java:401)
at org.apache.maven.plugin.assembly.AssemblyMojo.createArchive(AssemblyMojo.java:187)
at org.apache.maven.plugin.assembly.AssemblyMojo.execute(AssemblyMojo.java:163)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:417)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:554)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:517)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:498)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:233)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:149)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:217)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:247)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

I found this mail that seems to result from a failed integration build:
http://www.mail-archive.com/dev@maven.apache.org/msg39297.html

---
No further details from [MASSEMBLY-15](https://issues.apache.org/jira/browse/MASSEMBLY-15?redirect=false)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

sorry, but you must upgrade to the Maven 2.0 RC,
