### ISSUE TITLE
[MASSEMBLY-9] assembly plugin with jar-with-dependency fails if there is no classes

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#265]
**[Scokart Gilles](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gscokart)** opened **[MASSEMBLY-9](https://issues.apache.org/jira/browse/MASSEMBLY-9?redirect=false)** and commented

Here is the stack trace.

NB: This happens when we have a module that is no more than a regrouping of dependencies.

[INFO] Error creating assembly

Embedded error: c:\dev\data\nextMock_space\target\classes isn't a directory.
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error creating assembly
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:544)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:482)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:452)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav
a:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:214)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:316)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating assembly
at org.apache.maven.plugin.assembly.AssemblyMojo.execute(AssemblyMojo.java:171)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:399)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
... 16 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: c:\dev\data\nextMock_space\target\classes isn't a directory.
at org.codehaus.plexus.archiver.AbstractArchiver.addDirectory(AbstractArchiver.java:125)
at org.apache.maven.plugin.assembly.AssemblyMojo.processFileSets(AssemblyMojo.java:413)
at org.apache.maven.plugin.assembly.AssemblyMojo.createArchive(AssemblyMojo.java:187)
at org.apache.maven.plugin.assembly.AssemblyMojo.execute(AssemblyMojo.java:163)
... 18 more

---

**Issue Links:**
- [MASSEMBLY-5](https://issues.apache.org/jira/browse/MASSEMBLY-5) mvn assembly:assembly fails if there is no target directory already present

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

fix for MASSEMBLY-5 took care of this, even though they are different, as in 2.1 they delegate to the same method.
