### ISSUE TITLE
[MASSEMBLY-49] InvalidArtifactRTException is thrown when appendAssemblyId=false

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#298]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** opened **[MASSEMBLY-49](https://issues.apache.org/jira/browse/MASSEMBLY-49?redirect=false)** and commented

packaging=pom
appendAssemblyId=false
bind assembly:attached goal to package phase

here the build ouput

&mdash;
[INFO] [assembly:attached {execution: default}]
[INFO] Building zip: C:\Temp\m2test\archiver-maven-plugin-test\target\archiver-m
aven-plugin-test-1.0-beta-1-SNAPSHOT.zip
[INFO] -------------------------------------------------------------------------
&mdash;
[ERROR] FATAL ERROR
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] An invalid artifact was detected.

This artifact might be in your project's POM, or it might have been included tra
nsitively during the resolution process. Here is the information we do have for
this artifact:

    o GroupID:     org.codehaus.mojo.test
    o ArtifactID:  archiver-maven-plugin-test
    o Version:     1.0-beta-1-SNAPSHOT
    o Type:        zip

[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Trace
org.apache.maven.artifact.InvalidArtifactRTException: For artifact {org.codehaus
.mojo.test:archiver-maven-plugin-test:1.0-beta-1-SNAPSHOT:zip}: Attached artifac
ts must specify a classifier.
at org.apache.maven.project.artifact.AttachedArtifact.\<init>(AttachedArt
ifact.java:52)
at org.apache.maven.project.DefaultMavenProjectHelper.attachArtifact(Def
aultMavenProjectHelper.java:32)
at org.apache.maven.plugin.assembly.AbstractAssemblyMojo.execute(Abstrac
tAssemblyMojo.java:216)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:399)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:469)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:448)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:316)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Total time: 1 second
[INFO] Finished at: Mon Jan 02 02:32:50 CST 2006
[INFO] Final Memory: 2M/5M
[INFO] -------------------------------------------------------------------------
&mdash;

I think the root cause is in ProjectHelper plexus component

---
No further details from [MASSEMBLY-49](https://issues.apache.org/jira/browse/MASSEMBLY-49?redirect=false)

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

This is fixed in maven-2.0.1 where maven-project's AttachedArtifact has the fix to accept attched artifact without specifier

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I'd getting this with 2.0.2-SNAPSHOT, attachAssemblyId=false, fullName used to change the end id, not attached.
