### ISSUE TITLE
[MASSEMBLY-158] tempRoot directory not created, exceptions thrown when filtering files

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#331]
**[Daniel Kulp](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dkulp)** opened **[MASSEMBLY-158](https://issues.apache.org/jira/browse/MASSEMBLY-158?redirect=false)** and commented

The tempRoot directory isn't actually created before it attempts to write files into it.   Thus, creation of the files fails with FileNotFound exceptions.

The patch forces the directory to be created at the start of execute() and clears it up at the end.    It also updates the org/apache/maven/plugin/assembly/format/FileFormatter.java to make sure the directory is created first.

---

**Affects:** 2.2

**Attachments:**
- [assembly_temproot.patch](https://issues.apache.org/jira/secure/attachment/12713984/assembly_temproot.patch) (_3.36 kB_)

1 votes, 0 watchers

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

applied the patch, with modifications. I centralized the temp-dir creation and deletion to the AssemblyFileUtils class. Then, I moved the code to verify the existence of that temp dir to the DefaultAssemblyArchiver class, so it'll travel with the rest of the assembly main logic if we ever factor that API out of the assembly plugin.

**Comment by jira-importer** [comment]
**[Milos Kleint](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkleint)** commented

please remove the shutdown hook, it's causing problems in embedded environment.
I get this exception when running the plugin in netbeans. (actually I get the exception on IDE exit and it prevents a proper exiting.
The reason is that the maven build is run in a thread group (in the execution engine of netbeans) that doesn't exist anymore on IDE shutdown.

java.lang.IllegalThreadStateException
at java.lang.ThreadGroup.add(ThreadGroup.java:856)
at java.lang.Thread.start(Thread.java:573)
at java.lang.Shutdown.runHooks(Shutdown.java:128)
at java.lang.Shutdown.sequence(Shutdown.java:173)
at java.lang.Shutdown.exit(Shutdown.java:218)
at java.lang.Runtime.exit(Runtime.java:90)
at java.lang.System.exit(System.java:869)
at org.netbeans.TopSecurityManager.exit(TopSecurityManager.java:128)
at org.netbeans.core.NbTopManager$3.run(NbTopManager.java:408)
at org.openide.util.Task.run(Task.java:222)
at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:541)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:963)

**Comment by jira-importer** [comment]
**[Milos Kleint](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkleint)** commented

raising to blocker because using the plugin now has showstopper attributes for IDE integration.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

I removed the shutdown hook.
