### ISSUE TITLE
[MASSEMBLY-103] More powerful includes/excludes stuff in DependencySets in descriptors

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#350]
**[Richard van der Hoff](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=richvdh)** opened **[MASSEMBLY-103](https://issues.apache.org/jira/browse/MASSEMBLY-103?redirect=false)** and commented

A couple of other issues - http://jira.codehaus.org/browse/MASSEMBLY-90, http://jira.codehaus.org/browse/MASSEMBLY-41 - have pointed out the need for more powerful filtering of dependency sets in assembly descriptors. I wanted to take this further, so as to allow quite powerful boolean expressions for the description of dependencies. For example, the assembly extract below will include anything which is not a "zip" in the org.apache.maven.* or org.codehaus.* groups.

The attachment contains an implementation of this, and a couple of testcases for the new functionality.

\<dependencySet>
\<filter>
\<negate>false\</negate>
\<subfilters>
\<filter>
\<matchAll>false\</matchAll>
\<matchers>
\<matcher>
\<group>org.apache.maven.*\</group>
\</matcher>
\<matcher>
\<group>org.codehaus.*\</group>
\</matcher>
\</matchers>
\</filter>
\</subfilters>
\<matchers>
\<matcher>
\<type>zip\</type>
\</matcher>
\</matchers>
\</filter>
\</dependencySet>

---

**Affects:** 2.1

**Attachments:**
- [maven-assembly-plugin-filters.patch](https://issues.apache.org/jira/secure/attachment/12714198/maven-assembly-plugin-filters.patch) (_29.80 kB_)
- [maven-assembly-plugin-filters.v2.patch](https://issues.apache.org/jira/secure/attachment/12713981/maven-assembly-plugin-filters.v2.patch) (_38.20 kB_)

6 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Richard van der Hoff](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=richvdh)** commented

doh. Now imagine that the xml snippet had "\<negate>true\</negate>", and that jira hadn't eaten all the lovely indentation, and that would work much better.

**Comment by jira-importer** [comment]
**[Chris Chen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ckchris)** commented

I'm getting building errors when I run "mvn compile" with your patch.  Also, the AssemblyMojoTest.java also gets patch problems, which isn't too difficult to resolve.  I checked out the same revision that your patch is diff'ed against and I am still having problems.

```
java.lang.ArrayIndexOutOfBoundsException: 0
        at org.apache.maven.tools.plugin.extractor.java.JavaMojoDescriptorExtractor.getJavaClass(JavaMojoDescriptorExtractor.java:467)
        at org.apache.maven.tools.plugin.extractor.java.JavaMojoDescriptorExtractor.execute(JavaMojoDescriptorExtractor.java:486)
        at org.apache.maven.tools.plugin.scanner.DefaultMojoScanner.populatePluginDescriptor(DefaultMojoScanner.java:69)
        at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:99)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:475)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:454)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

**Comment by jira-importer** [comment]
**[Chris Chen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ckchris)** commented

Oh, missed a few more lines of output that occurs before the exception.  The output is after the modello generation.

```
[INFO] [modello:xpp3-reader {execution: descriptor}]
[INFO] outputDirectory: /Users/ckchris/proj/maven-assembly-plugin-2.1/target/generated-sources/modello
[INFO] [modello:xpp3-writer {execution: descriptor}]
[INFO] outputDirectory: /Users/ckchris/proj/maven-assembly-plugin-2.1/target/generated-sources/modello
[INFO] [modello:java {execution: descriptor}]
[INFO] outputDirectory: /Users/ckchris/proj/maven-assembly-plugin-2.1/target/generated-sources/modello
[INFO] [modello:xsd {execution: descriptor}]
[INFO] outputDirectory: /Users/ckchris/proj/maven-assembly-plugin-2.1/target/generated-site/xsd
[INFO] [modello:xpp3-reader {execution: component}]
[INFO] outputDirectory: /Users/ckchris/proj/maven-assembly-plugin-2.1/target/generated-sources/modello
[INFO] [modello:java {execution: component}]
[INFO] outputDirectory: /Users/ckchris/proj/maven-assembly-plugin-2.1/target/generated-sources/modello
[INFO] [modello:xsd {execution: component}]
[INFO] outputDirectory: /Users/ckchris/proj/maven-assembly-plugin-2.1/target/generated-site/xsd
[INFO] [plugin:descriptor]
[INFO] Using 2 extractors.
[INFO] Applying extractor for language: java
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] 0
[INFO] ------------------------------------------------------------------------
[INFO] Trace

```

**Comment by jira-importer** [comment]
**[Richard van der Hoff](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=richvdh)** commented

The compile-time error is due to source files which have been deleted... They're reduced to zero size by the patch, but not removed. Try:

$ find src/main/java -name *.java -size 0 | xargs rm

Regarding the patch problem; there have been a few changes to AssemblyMojoTest.java since I made that patch, but it still applies fine for me:

$ svn co http://svn.apache.org/repos/asf/maven/plugins/trunk/maven-assembly-plugin maven-assembly-plugin-trunk
...
$ cd maven-assembly-plugin-trunk
$ patch -p1 < ~/tmp/maven-assembly-plugin-filters.v2.patch
patching file src/test/java/org/apache/maven/plugin/assembly/AssemblyMojoTest.java
Hunk #1 succeeded at 286 (offset 3 lines).
patching file src/test/plugin-configs/assembly/depSet-filter-plugin-config.xml
patching file src/test/resources/assemblies/dependencySet-filter.xml
patching file src/main/mdo/component.mdo
patching file src/main/mdo/descriptor.mdo
patching file src/main/java/org/apache/maven/plugin/assembly/filter/AssemblyExcludesArtifactFilter.java
patching file src/main/java/org/apache/maven/plugin/assembly/filter/ArtifactMatchFilter.java
patching file src/main/java/org/apache/maven/plugin/assembly/filter/CompoundArtifactFilter.java
patching file src/main/java/org/apache/maven/plugin/assembly/filter/AssemblyIncludesArtifactFilter.java
patching file src/main/java/org/apache/maven/plugin/assembly/filter/AssemblyScopeArtifactFilter.java
patching file src/main/java/org/apache/maven/plugin/assembly/filter/BaseArtifactFilter.java
patching file src/main/java/org/apache/maven/plugin/assembly/AbstractAssemblyMojo.java
patching file src/test/java/org/apache/maven/plugin/assembly/filter/ArtifactMatchFilterTest.java

**Comment by jira-importer** [comment]
**[Richard van der Hoff](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=richvdh)** commented

was there any interest in applying this patch? I see it has quite a few votes...

**Comment by jira-importer** [comment]
**[Richard van der Hoff](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=richvdh)** commented

oh, of course now the patch has bit-rotted. Meh, I hate it when that happens.

If there /is/ any interest in applying this, let me know and I shall see about updating it. If it's just going to stagnate again, i won't bother and will stick with my custom build of version 2.1 of the plugin.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

try:

\<dependencySet>
\<includes>
\<include>org.apache.maven:*:jar\</include>
\</includes>
\<excludes>
\<exclude>org.apache.maven:maven-artifact:*\</exclude>
\</excludes
\</dependencySet>

**Comment by jira-importer** [comment]
**[Richard van der Hoff](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=richvdh)** commented

Right, I guess that's a good solution (though I still maintain mine was more flexible :) ). Thanks!

A bit of documentation on the format of \<include> and \<exclude> wouldn't go amiss though O:-)

See also my comment on MASSEMBLY-90
