### ISSUE TITLE
[MASSEMBLY-79] Unable to generate modello:xdoc for the assembly plugin

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#373]
**[Wendy Smoak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wsmoak)** opened **[MASSEMBLY-79](https://issues.apache.org/jira/browse/MASSEMBLY-79?redirect=false)** and commented

I found that 'mvn site' for maven-assembly-plugin does not generate assembly.html

Brett suggested 'mvn modello:xdoc site' (and mentioned that he thought this should be done automatically since maven 2.0.3.)

See: http://www.nabble.com/Re%3A-Please-update-assembly-plugin-docs-p3813075.html

~/svn/maven/plugins/maven-assembly-plugin
$ mvn modello:xdoc -e
+ Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] Searching repository for plugin with prefix: 'modello'.
  [INFO] -------------------------------------------------------------------------
  &mdash;
  [INFO] Building Maven Assembly Plugin
  [INFO]    task-segment: [modello:xdoc]
  [INFO] -------------------------------------------------------------------------
  &mdash;
  [INFO] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus
  .velocity.ContextClassLoaderResourceLoader'.
  [INFO] Setting property: velocimacro.messages.on => 'false'.
  [INFO] Setting property: resource.loader => 'classpath'.
  [INFO] Setting property: resource.manager.logwhenfound => 'false'.
  [INFO] **************************************************************
  [INFO] Starting Jakarta Velocity v1.4
  [INFO] RuntimeInstance initializing.
  [INFO] Default Properties File: org\apache\velocity\runtime\defaults\velocity.properties
  [INFO] Default ResourceManager initializing. (class org.apache.velocity.runtime.resource.ResourceManagerImpl)
  [INFO] Resource Loader Instantiated: org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
  [INFO] ClasspathResourceLoader : initialization starting.
  [INFO] ClasspathResourceLoader : initialization complete.
  [INFO] ResourceCache : initialized. (class org.apache.velocity.runtime.resource.ResourceCacheImpl)
  [INFO] Default ResourceManager initialization complete.
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Literal
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Macro
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Parse
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Include
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
  [INFO] Created: 20 parsers.
  [INFO] Velocimacro : initialization starting.
  [INFO] Velocimacro : adding VMs from VM library template : VM_global_library.vm
  [ERROR] ResourceManager : unable to find resource 'VM_global_library.vm' in any resource loader.
  [INFO] Velocimacro : error using  VM library template VM_global_library.vm : org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'VM_global_library.vm'
  [INFO] Velocimacro :  VM library template macro registration complete.
  [INFO] Velocimacro : allowInline = true : VMs can be defined inline in templates

[INFO] Velocimacro : allowInlineToOverride = false : VMs defined inline may NOT replace previous VM definitions
[INFO] Velocimacro : allowInlineLocal = false : VMs defined inline will be  global in scope if allowed.
[INFO] Velocimacro : initialization complete.
[INFO] Velocity successfully started.
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] One or more required plugin parameters are invalid/missing for 'modello:x
doc'

[0] inside the definition for plugin: 'modello-maven-plugin'specify the following:

\<configuration>
...
\<model>VALUE\</model>
\</configuration>

-OR-

on the command line, specify: '-Dmodel=VALUE'

[1] inside the definition for plugin: 'modello-maven-plugin'specify the following:

\<configuration>
...
\<version>VALUE\</version>
\</configuration>

-OR-

on the command line, specify: '-Dversion=VALUE'

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error configuring: org.c
odehaus.modello:modello-maven-plugin. Reason: Invalid or missing parameters: [Mo
jo parameter [name: 'model'; alias: 'null'], Mojo parameter [name: 'version'; al
ias: 'null']] for mojo: org.codehaus.modello:modello-maven-plugin:1.0-alpha-8:xdoc
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:563)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:488)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.plugin.PluginParameterException: Error configuring:
org.codehaus.modello:modello-maven-plugin. Reason: Invalid or missing parameters
: [Mojo parameter [name: 'model'; alias: 'null'], Mojo parameter [name: 'version
'; alias: 'null']] for mojo: org.codehaus.modello:modello-maven-plugin:1.0-alpha-8:xdoc
at org.apache.maven.plugin.DefaultPluginManager.checkRequiredParameters(DefaultPluginManager.java:809)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:574)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:390)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
... 16 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 seconds
[INFO] Finished at: Fri Apr 07 18:09:32 GMT-07:00 2006
[INFO] Final Memory: 5M/9M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.1

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

mvn site

works for me now. Brett, is there something else that needs to be done?

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

verified.
