### ISSUE TITLE
[MASSEMBLY-248] version was null for junit:junit

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#389]
**[Danilo Seki](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dseki)** opened **[MASSEMBLY-248](https://issues.apache.org/jira/browse/MASSEMBLY-248?redirect=false)** and commented

Another report for MASSEMBLY-214, but I will try to be more specific.
The stack trace is the same (included below just for easy reference), but this is the project configuration:
- Grand parent project with a dependency **management** to junit:junit:4.4 with scope test.

```
[INFO] [assembly:attached {execution: make-assembly}]
[INFO] Processing DependencySet (output=null)
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] version was null for junit:junit
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException: version was null for junit:junit
        at org.apache.maven.artifact.DefaultArtifact.getBaseVersion(DefaultArtifact.java:364)
        at org.apache.maven.artifact.DefaultArtifact.getId(DefaultArtifact.java:225)
        at org.apache.maven.shared.artifact.filter.ScopeArtifactFilter.include(ScopeArtifactFilter.java:142)
        at org.apache.maven.project.artifact.MavenMetadataSource.createArtifacts(MavenMetadataSource.java:345)
        at org.apache.maven.plugin.assembly.artifact.DefaultDependencyResolver.resolveDependencies(DefaultDependencyResolver.java:82)
        at org.apache.maven.plugin.assembly.archive.task.AddDependencySetsTask.resolveDependencyArtifacts(AddDependencySetsTask.java:155)
        at org.apache.maven.plugin.assembly.archive.task.AddDependencySetsTask.addDependencySet(AddDependencySetsTask.java:100)
        at org.apache.maven.plugin.assembly.archive.task.AddDependencySetsTask.execute(AddDependencySetsTask.java:90)
        at org.apache.maven.plugin.assembly.archive.phase.DependencySetAssemblyPhase.execute(DependencySetAssemblyPhase.java:54)
        at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:98)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:278)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:280)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

- Grand parent project with plugin **management** configuring the assembly plugin:

```xml
<plugin>
    <artifactId>maven-assembly-plugin</artifactId>
    <configuration>
        <descriptorSourceDirectory>src/assembly</descriptorSourceDirectory>
    </configuration>
    <executions>
        <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
                <goal>attached</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

- Project POM references the junit dependency and assembly plugin:

```xml
<dependencies>
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.4</version>
    </dependency>
</dependencies>

<build>
    <plugins>
        <plugin>
            <artifactId>maven-assembly-plugin</artifactId>
        </plugin>
    </plugins>
</build>
```

By grand parent project I mean that the modules has a parent and the parent project also has a parent, but just the direct parent lists the project as module.
I "resolved" this by specifing the junit dependecy version for 4.4, but that is not quite right.

---

**Affects:** 2.2-beta-1

**Issue Links:**
- [MASSEMBLY-214](https://issues.apache.org/jira/browse/MASSEMBLY-214) java.lang.NullPointerException: version was null for junit:junit

5 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Danilo Seki](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dseki)** commented

Another piece of information:
This is the correction (project POM):

```xml
<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.4</version>
</dependency>
```

Also, the same situation ocurrs with a log4j runtime dependency, but in this case there is no error.

**Comment by jira-importer** [comment]
**[Tom Nichols](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tomstrummer)** commented

I just ran into this issue as well.  To reproduce:

```
$ svn co -r 782 http://svn.codehaus.org/gmod/httpbuilder/trunk http-builder
$ cd http-builder
```

Edit pom.xml line 84, change the scope to 'provided' (this should be the 'xercesImpl' dependency with a specified version range).

```
$ mvn assembly:assembly -Dmaven.test.skip=true

....

[INFO] [assembly:attached {execution: default}]
[INFO] Reading assembly descriptor: src/main/assembly/all.xml
[INFO] Processing DependencySet (output=target/dependencies)
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] version was null for xerces:xercesImpl
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException: version was null for xerces:xercesImpl
        at org.apache.maven.artifact.DefaultArtifact.getBaseVersion(DefaultArtifact.java:382)
        at org.apache.maven.artifact.DefaultArtifact.getId(DefaultArtifact.java:226)
        at org.apache.maven.shared.artifact.filter.ScopeArtifactFilter.include(ScopeArtifactFilter.java:142)
        at org.apache.maven.project.artifact.MavenMetadataSource.createArtifacts(MavenMetadataSource.java:455)
        at org.apache.maven.plugin.assembly.artifact.DefaultDependencyResolver.resolveDependencies(DefaultDependencyResolver.java:123)
        at org.apache.maven.plugin.assembly.archive.task.AddDependencySetsTask.resolveDependencyArtifacts(AddDependencySetsTask.java:205)
        at org.apache.maven.plugin.assembly.archive.task.AddDependencySetsTask.addDependencySet(AddDependencySetsTask.java:132)
        at org.apache.maven.plugin.assembly.archive.task.AddDependencySetsTask.execute(AddDependencySetsTask.java:116)
        at org.apache.maven.plugin.assembly.archive.phase.DependencySetAssemblyPhase.execute(DependencySetAssemblyPhase.java:74)
        at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:129)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:322)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)
....
```

As a work-around, I've marked the dependency as 'optional' but if that tag is removed the behavior is the same.
