### ISSUE TITLE
[MASSEMBLY-290] Improve error reporting in case of unlocatable component descriptor

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#459]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** opened **[MASSEMBLY-290](https://issues.apache.org/jira/browse/MASSEMBLY-290?redirect=false)** and commented

That's not really user-friendly:

```
[INFO] [assembly:attached {execution: make-assemblies}]
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
        at org.apache.maven.plugin.assembly.io.DefaultAssemblyReader.mergeComponentsWithMainAssembly(DefaultAssemblyReader.java:454)
        at org.apache.maven.plugin.assembly.io.DefaultAssemblyReader.readAssembly(DefaultAssemblyReader.java:366)
        at org.apache.maven.plugin.assembly.io.DefaultAssemblyReader.addAssemblyFromDescriptor(DefaultAssemblyReader.java:332)
        at org.apache.maven.plugin.assembly.io.DefaultAssemblyReader.readAssemblies(DefaultAssemblyReader.java:193)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:296)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:447)
```

---

**Affects:** 2.2-beta-2

**Attachments:**
- [missing-component-descriptor.patch](https://issues.apache.org/jira/secure/attachment/12714214/missing-component-descriptor.patch) (_755 bytes_)

**Comment by jira-importer** [comment]
**[Paul Gier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pgier)** commented

Fixed in [r783381](http://svn.apache.org/viewvc?view=rev&revision=783381).
