### ISSUE TITLE
[MASSEMBLY-297] Assembly broke on GNU/Linux - NullPointerException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#466]
**[Robin Roos](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=robinroos2)** opened **[MASSEMBLY-297](https://issues.apache.org/jira/browse/MASSEMBLY-297?redirect=false)** and commented

I have an assembly descriptor  "src/main/assembly/unix.xml" which works on Windows but broke on Unix.  When I commented out the following lines of the assembly descriptor then it worked on Unix:

    <fileSet>
        <includes>
            <include>README*</include>
            <include>LICENSE*</include>
            <include>NOTICE*</include>
        </includes>
        <filtered>true</filtered>
    </fileSet>

I have no README*, LICENSE* or NOTICE* files in my src tree.

I have no filters defined in my pom.xml.  The \<filtered>true\</filtered> makes the assembly invoke filtering if the pom does define filters.

With the above \<fileSet> included in the \<fileSets> element I get the following exception on assembly (on Unix only):

(I had variously used lib and /lib as target directory when debugging this so ignore discrepencies in this regard)

[INFO] Processing DependencySet (output=lib)
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at java.io.File.&lt;init&gt;(File.java:194)
at org.apache.maven.shared.model.fileset.util.FileSetManager.scan(FileSetManager.java:598)
at org.apache.maven.shared.model.fileset.util.FileSetManager.getIncludedFiles(FileSetManager.java:186)
at org.apache.maven.plugin.assembly.format.FileSetFormatter.formatFileSetForAssembly(FileSetFormatter.java:67)
at org.apache.maven.plugin.assembly.archive.task.AddFileSetsTask.addFileSet(AddFileSetsTask.java:133)
at org.apache.maven.plugin.assembly.archive.task.AddFileSetsTask.execute(AddFileSetsTask.java:87)
at org.apache.maven.plugin.assembly.archive.phase.FileSetAssemblyPhase.execute(FileSetAssemblyPhase.java:54)
at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:129)
at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:322)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:447)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:493)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:463)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:224)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:333)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:126)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:282)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9 seconds
[INFO] Finished at: Thu Mar 13 12:42:17 GMT 2008
[INFO] Final Memory: 19M/470M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.2-beta-1, 2.2-beta-2

**Attachments:**
- [buildlog.txt](https://issues.apache.org/jira/secure/attachment/12714282/buildlog.txt) (_4.43 kB_)
- [MASSEMBLY-297.zip](https://issues.apache.org/jira/secure/attachment/12714037/MASSEMBLY-297.zip) (_3.37 kB_)
- [unix.xml](https://issues.apache.org/jira/secure/attachment/12714172/unix.xml) (_3.76 kB_)

**Issue Links:**
- [MASSEMBLY-342](https://issues.apache.org/jira/browse/MASSEMBLY-342) NPE when filtering fileSet
 (_**"duplicates"**_)
- [MSHARED-55](https://issues.apache.org/jira/browse/MSHARED-55) NLP IF no fileset directory specified.
 (_**"depends upon"**_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

I got the maven-assembly-plugin:2.2-beta-2 failing on the attached mini project even on a Windows box. It works if either
- using 2.2-beta-1 or
- disabling filtering for the fileset in question

Robin, can it be that you use auto-update for the plugins and that your tries on Windows simply used a different version of the plugin than on Unix?

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

could it be because the directory is not specified for this fileSet?

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> could it be because the directory is not specified for this fileSet?
> Yes, at the end of the day, that's why the NPE comes up.

However, leaving the directory unspecified is in general a supported use case. E.g. `AddFileSetsTask.getFileSetDirectory()` assumes the base directory in case the fileset's directory is not set, similar to `ModuleSetAssemblyPhase.createFileSet()`.

Seems the `FileSetFormatter` simply needs the same null check logic.
