### ISSUE TITLE
[MASSEMBLY-345] a"ppxml attribute is required" error when making ears with the assembly plugin

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#512]
**[Petar Tahchiev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paranoiabla)** opened **[MASSEMBLY-345](https://issues.apache.org/jira/browse/MASSEMBLY-345?redirect=false)** and commented

So what I am doing is trying to make ears with the assembly plugin. For instance here is my assembly descriptor:

---

\<assembly>
	\<id>src\</id>
	\<formats>
		\<format>ear\</format>
	\</formats>	
	\<fileSets>
		\<fileSet>
			\<useDefaultExcludes>false\</useDefaultExcludes>
			\<includes>
				\<include>**\</include>
			\</includes>
		\</fileSet>
	\</fileSets>
\</assembly>

---

But instead, I get the following exception:

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to create assembly: Error creating assembly archive src: appxml attribute is required

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to create assembly: Error creating assembly archive src: appxml attribute is required
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:583)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly: Error creating assembly archive src: appxml attribute is required
at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:368)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
... 16 more
Caused by: org.apache.maven.plugin.assembly.archive.ArchiveCreationException: Error creating assembly archive src: appxml attribute is required
at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:136)
at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:322)
... 18 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: appxml attribute is required
at org.codehaus.plexus.archiver.ear.EarArchiver.initZipOutputStream(EarArchiver.java:90)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:340)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:249)
at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:762)
at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.createArchive(AssemblyProxyArchiver.java:496)
at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:132)
... 19 more:
[INFO] ----------------------

The problem is that the mojo uses the EarArchiver class from the plexusArchiver component
(http://fisheye.codehaus.org/browse/~raw,r=7140/plexus/plexus-components/trunk/plexus-archiver/src/main/java/org/codehaus/plexus/archiver/ear/EarArchiver.java)
in which method we see:

    // If no webxml file is specified, it's an error.
    if ( deploymentDescriptor == null && !isInUpdateMode() )
    {
        throw new ArchiverException( "appxml attribute is required" );
    }

It would be great if the assembly plugin provides some way to configure the descriptor.

Thanks a lot.

---

**Affects:** 2.2-beta-3

**Attachments:**
- [AbstractAssemblyMojo-345.patch](https://issues.apache.org/jira/secure/attachment/12714215/AbstractAssemblyMojo-345.patch) (_2.09 kB_)
- [AssemblyConfiguration-345.patch](https://issues.apache.org/jira/secure/attachment/12714248/AssemblyConfiguration-345.patch) (_674 bytes_)
- [DefaultAsemblyArchiver-345.patch](https://issues.apache.org/jira/secure/attachment/12714079/DefaultAsemblyArchiver-345.patch) (_1.66 kB_)
- [massembly-345.zip](https://issues.apache.org/jira/secure/attachment/12714284/massembly-345.zip) (_2.83 kB_)
- [massembly-345-integration-tests.txt](https://issues.apache.org/jira/secure/attachment/12713999/massembly-345-integration-tests.txt) (_2.88 kB_)

**Comment by jira-importer** [comment]
**[Petar Tahchiev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paranoiabla)** commented

This is the first part of the patch.

**Comment by jira-importer** [comment]
**[Petar Tahchiev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paranoiabla)** commented

The second part of the patch.
