### ISSUE TITLE
[MASSEMBLY-348] Configuration option to define a different extension.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#524]
**[Stefano Bagnara](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apache@bago.org)** opened **[MASSEMBLY-348](https://issues.apache.org/jira/browse/MASSEMBLY-348?redirect=false)** and commented

I have to create a "Avalon Phoenix" SAR file. It is a zip/jar, with a different extension.
The assembly plugin allow me to create a zip or a jar, let me choose the name, but I cannot alter the extension.

---

**Affects:** 2.2-beta-2

**Attachments:**
- [MASSEMBLY-348.diff](https://issues.apache.org/jira/secure/attachment/12714213/MASSEMBLY-348.diff) (_23.88 kB_)
- [plexus-archiver-sar-support-1.0.jar](https://issues.apache.org/jira/secure/attachment/12714308/plexus-archiver-sar-support-1.0.jar) (_5.32 kB_)
- [plexus-archiver-sar-support-1.0.jar](https://issues.apache.org/jira/secure/attachment/12713994/plexus-archiver-sar-support-1.0.jar) (_5.33 kB_)

2 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Stefano Bagnara](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apache@bago.org)** commented

This upgrade the mdo version to 1.1.1 adding the \<customExtension> property to the assmebly descriptor.

During the read it throw an error if customExtension is used in combination with multiple formats.

I added 2 test cases for the added property and tested it for Apache JAMES Server and it works fine.

**Comment by jira-importer** [comment]
**[Stefano Bagnara](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apache@bago.org)** commented

`@John`:  I guess this is the META-INF/plexus/components.xml file with something like this:

```xml
 
<component-set>
  <components>
    <!-- Archiver -->
    <component>
      <role>org.codehaus.plexus.archiver.Archiver</role>
      <role-hint>sar</role-hint>
      <implementation>org.codehaus.plexus.archiver.bzip2.JarArchiver</implementation>
      <instantiation-strategy>per-lookup</instantiation-strategy>
    </component> 
    <component>
      <role>org.codehaus.plexus.archiver.UnArchiver</role>
      <role-hint>sar</role-hint>
      <implementation>org.codehaus.plexus.archiver.zip.ZipUnArchiver</implementation>
      <instantiation-strategy>per-lookup</instantiation-strategy>
    </component>
    <component>
      <role>org.codehaus.plexus.components.io.resources.PlexusIoResourceCollection</role>
      <role-hint>sar</role-hint>
<implementation>org.codehaus.plexus.components.io.resources.PlexusIoZipFileResourceCollection</implementation>
      <instantiation-strategy>per-lookup</instantiation-strategy>
    </component> 
  </components>
</component-set>
```

will this work also for already defined extensions? (e.g: use the ziparchiver to create a file with a war extension)

**Comment by jira-importer** [comment]
**[Stefano Bagnara](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apache@bago.org)** commented

The "sar" enabler I'm trying...

**Comment by jira-importer** [comment]
**[Stefano Bagnara](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apache@bago.org)** commented

I added the components.xml as described above in a jar and added it to my assembly configuration:

```
<plugin>
  <artifactId>maven-assembly-plugin</artifactId>
  <version>2.2-beta-2</version>
  <dependencies>
    <dependency>
      <groupId>org.apache.james</groupId>
      <artifactId>plexus-archiver-sar-support</artifactId>
      <version>1.0</version>
    </dependency>
  </dependencies>
```

When I run my "package" for a "sar" format I get this output:

```
[INFO] [jar:jar]
[INFO] [jar:test-jar {execution: default}]
[INFO] [assembly:attached {execution: make-my-assembly}]
-----------------------------------------------------
this realm = app0.child-container[org.apache.maven.plugins:maven-assembly-plugin]
urls[0] = file:/C:/Users/bago/.m2/repository/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-2/maven-assembly-plugin-2.2-beta-2.jar
urls[1] = file:/C:/Users/bago/.m2/repository/org/apache/james/plexus-archiver-sar-support/1.0/plexus-archiver-sar-support-1.0.jar
urls[2] = file:/C:/Users/bago/.m2/repository/aspectj/aspectjrt/1.5.3/aspectjrt-1.5.3.jar
urls[3] = file:/C:/Users/bago/.m2/repository/org/codehaus/plexus/plexus-archiver/1.0-alpha-10/plexus-archiver-1.0-alpha-10.jar
urls[4] = file:/C:/Users/bago/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.jar
urls[5] = file:/C:/Users/bago/.m2/repository/org/codehaus/plexus/plexus-io/1.0-alpha-2/plexus-io-1.0-alpha-2.jar
urls[6] = file:/C:/Users/bago/.m2/repository/org/apache/maven/shared/file-management/1.1/file-management-1.1.jar
urls[7] = file:/C:/Users/bago/.m2/repository/org/apache/maven/shared/maven-shared-io/1.1/maven-shared-io-1.1.jar
urls[8] = file:/C:/Users/bago/.m2/repository/org/codehaus/plexus/plexus-active-collections/1.0-beta-2/plexus-active-collections-1.0-beta-2.jar
urls[9] = file:/C:/Users/bago/.m2/repository/org/apache/maven/maven-archiver/2.2/maven-archiver-2.2.jar
urls[10] = file:/C:/Users/bago/.m2/repository/org/apache/maven/shared/maven-repository-builder/1.0-alpha-2/maven-repository-builder-1.0-alpha-2.jar
urls[11] = file:/C:/Users/bago/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.0/maven-common-artifact-filters-1.0.jar
urls[12] = file:/C:/Users/bago/.m2/repository/org/apache/maven/shared/maven-plugin-testing-harness/1.1/maven-plugin-testing-harness-1.1.jar
Number of imports: 6
import: org.codehaus.classworlds.Entry@4891bb28
import: org.codehaus.classworlds.Entry@f8e44ca4
import: org.codehaus.classworlds.Entry@c51bc9e7
import: org.codehaus.classworlds.Entry@bece5185
import: org.codehaus.classworlds.Entry@3fee8e37
import: org.codehaus.classworlds.Entry@3fee19d8


this realm = plexus.core
urls[0] = file:/c:/Program Files/Java/maven/bin/../lib/maven-2.0.9-uber.jar
Number of imports: 6
import: org.codehaus.classworlds.Entry@4891bb28
import: org.codehaus.classworlds.Entry@f8e44ca4
import: org.codehaus.classworlds.Entry@c51bc9e7
import: org.codehaus.classworlds.Entry@bece5185
import: org.codehaus.classworlds.Entry@3fee8e37
import: org.codehaus.classworlds.Entry@3fee19d8
-----------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to create assembly: Unable to obtain archiver for extension 'sar'
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to create assembly: Unable to obtain archiver for extension 'sar'
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:583)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:324)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly: Unable to obtain archiver for extension 'sar'
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:368)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
        ... 16 more
Caused by: org.apache.maven.plugin.assembly.archive.ArchiveCreationException: Unable to obtain archiver for extension 'sar'
        at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:144)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:322)
        ... 18 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21 seconds
[INFO] Finished at: Wed Sep 10 17:46:56 CEST 2008
[INFO] Final Memory: 16M/33M
[INFO] ------------------------------------------------------------------------
```

And it does not work.
If I use a format that is not declared in the attached jar then I get the same stack trace but I don't see all of the output with realms/urls/imports logs.

Am I missing something or I'm hitting a bug in the proposed alternative solution?

**Comment by jira-importer** [comment]
**[Stefano Bagnara](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apache@bago.org)** commented

Fixed file

**Comment by jira-importer** [comment]
**[Stefano Bagnara](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apache@bago.org)** commented

Here again. The issue was that I had a bad declaration in my components.xml (I was declaring org.codehaus.plexus.archiver.bzip2.JarArchiver as the implementation and it does not exist.. it must have been a typo..). I fixed it and now I'm able to build sar files!

I've attached the fixed file so anyone else reading this issue later will have a good example.

One last question: is there a way to declare a new plexus component directly in my module sources instead of having to create a jar for this declaration?

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Stefano, is it OK to close this issue now?
Should it be resolved as "closed" or "won't fix"?

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

pushing this off to 2.2 final since there is a fix in place for it already (or, considering the effort involved, 'workaround' might be a better term).

**Comment by jira-importer** [comment]
**[David Tombs](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dgtombs)** commented

John, did you ever write the documentation you talked about for this?

Furthermore, do you plan on implementing an easier fix for this? It would be pragmatic. What do you think about a configuration option to override the output filename? I would happily try to implement it.
