### ISSUE TITLE
[MASSEMBLY-403] No files is added for fileset

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#564]
**[Andy Yeung](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aymanson81)** opened **[MASSEMBLY-403](https://issues.apache.org/jira/browse/MASSEMBLY-403?redirect=false)** and commented

I donn't know if I should report to maven 2.1.0 or here. Just tell my problem here first.

I have an assembly file which work well using maven 2.0.9. After update to maven 2.1.0, the assembly output don't have any files defined in the fileset.

---

**Affects:** 2.2-beta-3

**Comment by jira-importer** [comment]
**[Andy Yeung](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aymanson81)** commented

The assembly file like this
\<fileSets>
\<fileSet>
\<directory>${basedir}/target/server\</directory>
\<outputDirectory>/\</outputDirectory>
\<lineEnding>keep\</lineEnding>			
\<excludes>
\<exclude>**/*.sh\</exclude>
\<exclude>**/*.bat\</exclude>
\</excludes>
\</fileSet>
...
\</fileSets>

Using the -X option show something like this
[DEBUG] After assembly is interpolated:

\<?xml version="1.0" encoding="UTF-8"?>\<assembly>

\<id>andy\</id>
\<formats>
\<format>zip\</format>
\</formats>
\<includeBaseDirectory>false\</includeBaseDirectory>
\<fileSets>
\<fileSet>
\<directory>D\:\\andy\\ota\\tz-jboss-env/target/server\</directory>
\<lineEnding>keep\</lineEnding>
\<outputDirectory>/\</outputDirectory>
\<excludes>
\<exclude>**/*.sh\</exclude>
\<exclude>**/\*.bat\</exclude>
\</excludes>
\</fileSet>
\<fileSet>
\<directory>D\:\\andy\\ota\\tz-jboss-env/target/server\</directory>
\<lineEnding>unix\</lineEnding>
\<outputDirectory>/\</outputDirectory>
\<includes>
\<include>\*.sh\</include>
\</includes>
\<fileMode>755\</fileMode>
\</fileSet>
\<fileSet>
\<directory>D\:\\andy\\ota\\tz-jboss-env/target/server\</directory>
\<lineEnding>dos\</lineEnding>
\<filtered>true\</filtered>
\<outputDirectory>/\</outputDirectory>
\<includes>
\<include>\*.bat\</include>
\</includes>
\<fileMode>755\</fileMode>
\</fileSet>
\<fileSet>
\<directory>D\:\\andy\\ota\\tz-jboss-env/target/server-andy\</directory>
\<outputDirectory>/\</outputDirectory>
\<excludes>
\<exclude>**/*.sh\</exclude>
\<exclude>**/\*.bat\</exclude>
\</excludes>
\</fileSet>
\<fileSet>
\<directory>D\:\\andy\\ota\\tz-jboss-env/target/server-andy\</directory>
\<lineEnding>unix\</lineEnding>
\<outputDirectory>/\</outputDirectory>
\<includes>
\<include>\*.sh\</include>
\</includes>
\<fileMode>755\</fileMode>
\</fileSet>
\<fileSet>
\<directory>D\:\\andy\\ota\\tz-jboss-env/target/server-andy\</directory>
\<lineEnding>dos\</lineEnding>
\<outputDirectory>/\</outputDirectory>
\<includes>
\<include>*.bat\</include>
\</includes>
\<fileMode>755\</fileMode>
\</fileSet>
\</fileSets>
\</assembly>

[DEBUG] All known ContainerDescritporHandler components: [plexus]
[DEBUG] FileSet[] dir perms: 40755 file perms: 100644 lineEndings: keep
[DEBUG] The archive base directory is 'null'
[DEBUG] FileSet[] dir perms: 40755 file perms: 100644 lineEndings: unix
[DEBUG] The archive base directory is 'null'
[DEBUG] FileSet[] dir perms: 40755 file perms: 100644 lineEndings: dos
[DEBUG] The archive base directory is 'null'
[DEBUG] FileSet[] dir perms: 40755 file perms: 100644
[DEBUG] The archive base directory is 'null'
[DEBUG] FileSet[] dir perms: 40755 file perms: 100644 lineEndings: unix
[DEBUG] The archive base directory is 'null'
[DEBUG] FileSet[] dir perms: 40755 file perms: 100644 lineEndings: dos
[DEBUG] The archive base directory is 'null'
[DEBUG] No dependency sets specified.
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to create assembly: Error creating assembly archive andy: You must set at least one file.

[INFO] ------------------------------------------------------------------------

But if I remove the ${basedir} in the assembly file. The build go successfully. I wonder if maven 2.1.0 change the representation of basedir and assembly plugin intrepret wrongly and cause the build failed.
I also got some exception dump using -X just happened before the start of assembly plugin. I don't know if it is related.

These will use the artifact files already in the core ClassRealm instead, to allow them to be included in PluginDescript
or.getArtifacts().

[DEBUG] Cannot find ArtifactResolver with hint: project-cache-aware
org.codehaus.plexus.component.repository.exception.ComponentLookupException: Component descriptor cannot be found in the
component repository: org.apache.maven.artifact.resolver.ArtifactResolverproject-cache-aware.
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:323)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:312)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.apache.maven.shared.repository.DefaultRepositoryAssembler.contextualize(DefaultRepositoryAssembler.java:7
21)
at org.codehaus.plexus.personality.plexus.lifecycle.phase.ContextualizePhase.execute(ContextualizePhase.java:20)

    at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
    at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManag

er.java:105)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManag
er.java:95)
at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponent
Manager.java:92)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentCompo
ser.java:129)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assembleComponent(FieldComponentComposer.jav
a:73)
at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentC
omposerManager.java:68)
at org.codehaus.plexus.DefaultPlexusContainer.composeComponent(DefaultPlexusContainer.java:1486)
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:29)
at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManag
er.java:105)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManag
er.java:95)
at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponent
Manager.java:92)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.codehaus.plexus.DefaultPlexusContainer.lookupList(DefaultPlexusContainer.java:423)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentCompo
ser.java:111)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assembleComponent(FieldComponentComposer.jav
a:73)
at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentC
omposerManager.java:68)
at org.codehaus.plexus.DefaultPlexusContainer.composeComponent(DefaultPlexusContainer.java:1486)
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:29)
at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManag
er.java:105)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManag
er.java:95)
at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponent
Manager.java:92)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentCompo
ser.java:129)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assembleComponent(FieldComponentComposer.jav
a:73)
at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentC
omposerManager.java:68)
at org.codehaus.plexus.DefaultPlexusContainer.composeComponent(DefaultPlexusContainer.java:1486)
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:29)
at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManag
er.java:105)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManag
er.java:95)
at org.codehaus.plexus.component.manager.PerLookupComponentManager.getComponent(PerLookupComponentManager.java:4
8)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:645)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:461)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:54
0)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkProjectLifecycle(DefaultLifecycleExecutor.java:1168)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkLifecycle(DefaultLifecycleExecutor.java:1004)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:627)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:553)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:523)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav
a:371)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[DEBUG] Cannot find ArtifactResolver with hint: default
org.codehaus.plexus.component.repository.exception.ComponentLookupException: Component descriptor cannot be found in the
component repository: org.apache.maven.artifact.resolver.ArtifactResolverdefault.
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:323)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:312)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.apache.maven.shared.repository.DefaultRepositoryAssembler.contextualize(DefaultRepositoryAssembler.java:7
21)
at org.codehaus.plexus.personality.plexus.lifecycle.phase.ContextualizePhase.execute(ContextualizePhase.java:20)

    at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
    at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManag

er.java:105)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManag
er.java:95)
at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponent
Manager.java:92)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentCompo
ser.java:129)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assembleComponent(FieldComponentComposer.jav
a:73)
at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentC
omposerManager.java:68)
at org.codehaus.plexus.DefaultPlexusContainer.composeComponent(DefaultPlexusContainer.java:1486)
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:29)
at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManag
er.java:105)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManag
er.java:95)
at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponent
Manager.java:92)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.codehaus.plexus.DefaultPlexusContainer.lookupList(DefaultPlexusContainer.java:423)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentCompo
ser.java:111)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assembleComponent(FieldComponentComposer.jav
a:73)
at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentC
omposerManager.java:68)
at org.codehaus.plexus.DefaultPlexusContainer.composeComponent(DefaultPlexusContainer.java:1486)
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:29)
at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManag
er.java:105)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManag
er.java:95)
at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponent
Manager.java:92)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentCompo
ser.java:129)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assembleComponent(FieldComponentComposer.jav
a:73)
at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentC
omposerManager.java:68)
at org.codehaus.plexus.DefaultPlexusContainer.composeComponent(DefaultPlexusContainer.java:1486)
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:29)
at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManag
er.java:105)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManag
er.java:95)
at org.codehaus.plexus.component.manager.PerLookupComponentManager.getComponent(PerLookupComponentManager.java:4
8)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:645)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:461)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:54
0)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkProjectLifecycle(DefaultLifecycleExecutor.java:1168)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkLifecycle(DefaultLifecycleExecutor.java:1004)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:627)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:553)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:523)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav
a:371)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-3:attached' -->
[DEBUG]   (s) appendAssemblyId = true
[DEBUG]   (f) attach = false
[DEBUG]   (s) basedir = D:\andy\ota\tz-jboss-env
[DEBUG]   (s) descriptors = [target/assembly/assembly.xml]
[DEBUG]   (f) dryRun = false
[DEBUG]   (s) finalName = tz-jboss-env-1.0.0-SNAPSHOT
[DEBUG]   (f) ignoreDirFormatExtensions = true
[DEBUG]   (s) ignoreMissingDescriptor = false
[DEBUG]   (s) includeSite = false
[DEBUG]   (s) localRepository = Repository[local|file://d:\repository]
[DEBUG]   (f) mavenSession = org.apache.maven.execution.MavenSession@716cb7
[DEBUG]   (s) outputDirectory = D:\andy\ota\tz-jboss-env\assembly\andy
[DEBUG]   (f) project = MavenProject: com.travelzen:tz-jboss-env:1.0.0-SNAPSHOT @ D:\andy\ota\tz-jboss-env\pom.xml
[DEBUG]   (s) reactorProjects = [MavenProject: com.travelzen:tz-jboss-env:1.0.0-SNAPSHOT @ D:\andy\ota\tz-jboss-env\pom.
xml]
[DEBUG]   (f) remoteRepositories = [Repository[repo](http://repo.tz-dev.com:8081/artifactory/repo), Repository[repo-snaps
hot|http://repo.tz-dev.com:8081/artifactory/repo], Repository[central](http://repo1.maven.org/maven2)]
[DEBUG]   (s) siteDirectory = D:\andy\ota\tz-jboss-env\target\site
[DEBUG]   (f) skipAssembly = false
[DEBUG]   (s) tarLongFileMode = warn
[DEBUG]   (s) tempRoot = D:\andy\ota\tz-jboss-env\target\archive-tmp
[DEBUG]   (s) workDirectory = D:\andy\ota\tz-jboss-env\target\assembly\work
[DEBUG]   - end configuration --
[INFO] [assembly:attached {execution: zip}]
[INFO] Reading assembly descriptor: target/assembly/assembly.xml

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

should be fixed by now
