### ISSUE TITLE
[MASSEMBLY-471] [Multi-projects] Define maven-assembly-plugin in root pom.xml causes plugin's dependencies of child modules failed.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#633]
**[julien soula](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jsoula)** opened **[MASSEMBLY-471](https://issues.apache.org/jira/browse/MASSEMBLY-471?redirect=false)** and commented

I have a multi-module project (see attachment):
* pom.xml: Define the version of the plugin maven-assembly-plugin
* assembly: Jar project, contains an assembly descriptor
* livraison: Project for building assembly artifact. Use the previous assembly descriptor via dependencies. Attach assembly on the install phase.

In the root directory, launch `mvn clean install` cause build failed:

```

[INFO] ------------------------------------------------------------------------
[INFO] Building Unnamed - fr.jsoula:livraison:pom:1.0-SNAPSHOT
[INFO]    task-segment: [clean, install]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean {execution: default-clean}]
[INFO] [site:attach-descriptor {execution: default-attach-descriptor}]
[INFO] [install:install {execution: default-install}]
[INFO] Installing D:\perso\MyProjets\bug-maven-assembly\livraison\pom.xml to D:\Documents\jsoula\.m2\repository\fr\jsoula\livraiso
n\1.0-SNAPSHOT\livraison-1.0-SNAPSHOT.pom
[INFO] [assembly:directory-single {execution: make-assembly}]
[INFO] Reading assembly descriptor: assembly-test.xml
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error reading assembly descriptors: Error locating assembly descriptor: assembly-test.xml

[1] [INFO] Searching for file location: D:\perso\MyProjets\bug-maven-assembly\livraison\assembly-test.xml

[2] [INFO] File: D:\perso\MyProjets\bug-maven-assembly\livraison\assembly-test.xml does not exist.

[3] [INFO] Invalid artifact specification: 'assembly-test.xml'. Must contain at least three fields, separated by ':'.

[4] [INFO] Failed to resolve classpath resource: assemblies/assembly-test.xml from classloader: org.codehaus.classworlds.RealmClas
sLoader@b7c0b7c

[5] [INFO] Failed to resolve classpath resource: assembly-test.xml from classloader: org.codehaus.classworlds.RealmClassLoader@b7c
0b7c

[6] [INFO] File: D:\perso\MyProjets\bug-maven-assembly\assembly-test.xml does not exist.

[7] [INFO] Building URL from location: assembly-test.xml
Error:
java.net.MalformedURLException: no protocol: assembly-test.xml
       at java.net.URL.<init>(URL.java:567)
       at java.net.URL.<init>(URL.java:464)
       at java.net.URL.<init>(URL.java:413)
       at org.apache.maven.shared.io.location.URLLocatorStrategy.resolve(URLLocatorStrategy.java:54)
       at org.apache.maven.shared.io.location.Locator.resolve(Locator.java:81)
       at org.apache.maven.plugin.assembly.io.DefaultAssemblyReader.addAssemblyFromDescriptor(DefaultAssemblyReader.java:309)
       at org.apache.maven.plugin.assembly.io.DefaultAssemblyReader.readAssemblies(DefaultAssemblyReader.java:140)
       at org.apache.maven.plugin.assembly.mojos.AbstractDirectoryMojo.execute(AbstractDirectoryMojo.java:49)
       at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
       at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
       at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
       at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
       at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
       at java.lang.reflect.Method.invoke(Method.java:599)
       at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
       at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
       at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
       at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

But if i launch `mvn -f livraison/pom.xml clean install`, the build works.

Seems to be a plugin classpath problem but don't know if it causes by Maven or by the plugin.

---

**Affects:** 2.2-beta-5

**Attachments:**
- [bug-maven-assembly.zip](https://issues.apache.org/jira/secure/attachment/12714112/bug-maven-assembly.zip) (_5.35 kB_)

**Comment by jira-importer** [comment]
**[julien soula](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jsoula)** commented

A workaround is to duplicate dependencies on the declaration of the maven-plugin-assembly in the root pom.xml

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

in Maven 2.x, plugin-level dependencies will only be picked up from maven's first encounter with the plugin.

It's critical to list all plugin-level dependencies in a pluginManagement section of the parent POM to ensure they are included. This is a Maven design issue, not a problem with the assembly plugin.
