### ISSUE TITLE
[MASSEMBLY-556] mvn assembly:assembly NPEs with install:install-file'd artifacts

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#711]
**[Chris West (Faux)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=faux)** opened **[MASSEMBLY-556](https://issues.apache.org/jira/browse/MASSEMBLY-556?redirect=false)** and commented

I have 3rd-party jars installed via. `mvn install:install-file`.  This causes `mvn assembly:assembly` to NPE around:

```
Caused by: java.lang.NullPointerException
	at org.apache.maven.artifact.repository.metadata.AbstractRepositoryMetadata.getLocalFilename(AbstractRepositoryMetadata.java:61)
	at org.apache.maven.artifact.repository.layout.DefaultRepositoryLayout.pathOfLocalRepositoryMetadata(DefaultRepositoryLayout.java:72)
...
```

To reproduce, first, install:install-file a random file:

```
mvn install:install-file -Dfile=pom.xml -DgroupId=com.goeswhere.test -DartifactId=a -Dversion=0 -Dpackaging=jar
```

Then, create pom.xml (attached):

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.goeswhere.test</groupId>
	<artifactId>b</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>jar</packaging>

	<dependencies>
		<dependency>
			<groupId>com.goeswhere.test</groupId>
			<artifactId>a</artifactId>
			<version>0</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<descriptors>
						<descriptor>./repository.xml</descriptor>
					</descriptors>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

and repository.xml (attached):

```xml

<assembly
	xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2 http://maven.apache.org/xsd/assembly-1.1.2.xsd">
	<id>repository</id>
	<formats>
		<format>jar</format>
	</formats>
	<repositories>
		<repository>
			<includeMetadata>true</includeMetadata>
			<outputDirectory>maven2</outputDirectory>
		</repository>
	</repositories>
</assembly>
```

And run `mvn assembly:assembly`.  See attached build.log.

---

**Affects:** 2.2-beta-5

**Attachments:**
- [build.log](https://issues.apache.org/jira/secure/attachment/12714338/build.log) (_74.74 kB_)
- [massembly-556.tar.gz](https://issues.apache.org/jira/secure/attachment/12714051/massembly-556.tar.gz) (_869 bytes_)
- [massembly-556-2.tar.gz](https://issues.apache.org/jira/secure/attachment/12714316/massembly-556-2.tar.gz) (_869 bytes_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12714232/pom.xml) (_931 bytes_)
- [repository.xml](https://issues.apache.org/jira/secure/attachment/12714296/repository.xml) (_513 bytes_)

4 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Martin Ellis](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mart)** commented

I've been able to reproduce this bug.  It seems to be caused by having a mirror defined in the settings.

See the attached project for an example.

Running with no mirror defined works correctly:
mvn package -s empty-settings.xml

... however, running with a mirror defined will fail:
mvn package -s mirror-settings.xml

My example settings use repo1.maven.org as the mirror, but I get the same behaviour with uk.maven.org, and with the url of our repository manager.

**Comment by jira-importer** [comment]
**[Martin Ellis](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mart)** commented

My user settings are based on the settings described here:
http://www.sonatype.com/books/nexus-book/reference/maven-sect-single-group.html

As a workaround, I've managed to build our project with the following settings file (note that 'nexus' resolves to our local Nexus instance):

```xml
<settings>
  <profiles>
    <profile>

      <id>no-mirrors</id>

      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>

      <repositories>
        <repository>
          <id>nexus</id>
          <layout>default</layout>
          <url>http://nexus/content/groups/public</url>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </repository>
      </repositories>

      <pluginRepositories>
        <pluginRepository>
          <id>nexus</id>
          <url>http://nexus/content/groups/public</url>
          <layout>default</layout>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </pluginRepository>
      </pluginRepositories>

    </profile>
  </profiles>
</settings>
```

**Comment by jira-importer** [comment]
**[Martin Ellis](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mart)** commented

Attaching massembly-556-2.tar.gz because I managed to compress the first archive twice.

Also: this issue doesn't seem to be specific to artifacts installed with install:install-file. (The project I've attached uses junit).

The issue title should probably be updated accordingly.

**Comment by jira-importer** [comment]
**[Martin Ellis](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mart)** commented

What's up with this ticket?

Looks like Benson Margulies just set the "Fix Version" to 2.3, but the "Fix Version" is still 'None' in the Details section. Also, the ticket doesn't appear at:

https://jira.codehaus.org/browse/MASSEMBLY/fixforversion/13669

Is JIRA confused (or just me)?

**Comment by jira-importer** [comment]
**[Martin Ellis](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mart)** commented

The patches I attached to MASSEMBLY-295 fix this issue.

**Comment by jira-importer** [comment]
**[Hal Deadman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hal.deadman)** commented

That's good. I hope the patch gets applied. I guess the easiest work-around for me now is to change includeMetadata option to false instead of true rather than removing mirrors, etc.

Thanks, Hal
