### ISSUE TITLE
[MASSEMBLY-602] Multiple Assemblies Causes Infinite Loop\Recursion

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#763]
**[Shaun](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=selliott@paml.com)** opened **[MASSEMBLY-602](https://issues.apache.org/jira/browse/MASSEMBLY-602?redirect=false)** and commented

    I have a custom assembly.xml on a project that also has a parent pom. In the parent pom, we specify: <appendAssemblyId>true</appendAssemblyId> As the default assembly (jar-with-dependencies-and-sources) is fine for 99% of our projects, however, in this instance, I need the custom assembly. However, the parent pom dicates: <appendAssemblyId>false</appendAssemblyId> Causing this error: Exception in thread "main" java.lang.StackOverflowError at sun.nio.cs.SingleByteEncoder.encodeArrayLoop(SingleByteEncoder.java:91) at sun.nio.cs.SingleByteEncoder.encodeLoop(SingleByteEncoder.java:130) at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:544) at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:252) at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:106) at java.io.OutputStreamWriter.write(OutputStreamWriter.java:190) at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:111) at java.io.PrintStream.write(PrintStream.java:476) at java.io.PrintStream.print(PrintStream.java:619) at org.apache.maven.cli.PrintStreamLogger.info(PrintStreamLogger.java:110) at org.codehaus.plexus.logging.AbstractLogger.info(AbstractLogger.java:51) at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:464) at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:467) at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:467) I believe this error to be related to PLXUTILS-148 

---

**Affects:** 2.2-beta-3, 2.2-beta-5, 2.2, 2.2.1, 2.2.2, 2.3

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Fixed in r1387716
