### ISSUE TITLE
[MASSEMBLY-646] OutOfMemory when running maven-assembly-plugin

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#807]
**[Bartosz Firyn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sarxos)** opened **[MASSEMBLY-646](https://issues.apache.org/jira/browse/MASSEMBLY-646?redirect=false)** and commented

I'm experiencing OutOfMemory error when maven build try to complete maven-assembly-plugin job.

Issue reproducible on Linux only.

The project I'm trying to build is [webcam-capture](https://github.com/sarxos/webcam-capture).

Command:

```
$ mvn clean package -P assembly -X
```

It hangs always in the same place:

```
[DEBUG] Adding file-set in: /home/sarxos/workspace-j2se/webcam-capture/webcam-capture/./src/example/java to archive location: examples/
```

In most cases process hangs and I'm getting OutOfMemory. Once I get this exception in the same time, before process started to allocate huge amount of memory OutOfMemory. OldGen is exhausted. Increasing memory to be allocated does not have any effect.

Not sure if exception below is cause or effect.

```
[DEBUG] Adding file-set in: /home/sarxos/workspace-j2se/webcam-capture/webcam-capture/./src/example/java to archive location: examples/
[DEBUG] Cannot find ArtifactResolver with hint: project-cache-aware
org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.apache.maven.artifact.resolver.ArtifactResolver
  roleHint: project-cache-aware
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:257)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:233)
	at org.apache.maven.shared.repository.DefaultRepositoryAssembler.contextualize(DefaultRepositoryAssembler.java:721)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.contextualize(PlexusLifecycleManager.java:317)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.manageLifecycle(PlexusLifecycleManager.java:292)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:148)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1018)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.sonatype.guice.bean.locators.EntryListAdapter$ValueIterator.next(EntryListAdapter.java:112)
	at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:181)
	at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:436)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.util.NoSuchElementException
	at java.util.Collections$EmptyIterator.next(Collections.java:2958)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
	... 43 more
```

---

**Affects:** 2.4

**Attachments:**
- [log.txt](https://issues.apache.org/jira/secure/attachment/12714344/log.txt) (_265.29 kB_)

**Issue Links:**
- [MASSEMBLY-651](https://issues.apache.org/jira/browse/MASSEMBLY-651) REOPEN - OutOfMemory when running maven-assembly-plugin
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Did you increase maven memory by setting maven opts ?

MAVEN_OPTS="-Xms256m -Xmx1024m -XX:MaxPermSize=256m"

**Comment by jira-importer** [comment]
**[Bartosz Firyn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sarxos)** commented

Hi,

Thank you for fast response :)

I've increased it from 256 to 512, and effect as the same, but now I tried with 1024, and it seems to work (at least it does not throw OutOfMemory), but mentioned exception is still there, visible in debug mode.

I'm a little bit surprised, since assembling was very fast on Windows, didn't use so huge amount of memory, and on my Ubuntu it takes 30x much more time and consumes up to 1GB. Donno why...

**Comment by jira-importer** [comment]
**[Bartosz Firyn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sarxos)** commented

Closing this issue due to configuration problem, not a real bug.
