### ISSUE TITLE
[MASSEMBLY-658] Assembly fails for multi-module project if webstart-maven-plugin is in use

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#823]
**[Robin Roos](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=robinroos2)** opened **[MASSEMBLY-658](https://issues.apache.org/jira/browse/MASSEMBLY-658?redirect=false)** and commented

The mvn invocation I used is:
mvn clean package

I attach a simple test case of a multi-module project. If the acme-jnlp module is commented out in the parent POM then the project builds successfully. If the acme-jnlp module is not commented out, then the assembly of acme-dist fails because of a NullPointerException.

acme-dist and acme-war to not rely on the artifacts generated by acme-jnlp. The mere fact that the plugin is executed causes the later module assembly to fail.

Modules have the following purposes:
acme-parent: parent project which contains the module
acme-jnlp: create JNLP and ZIP files not used by any other modules
acme-war: create a .WAR file
acme-dist: use assembly plugin to create a .ZIP containing the .WAR
acme-deploy: holds dependencies to other modules, but does nothing else

---

**Affects:** 2.4

**Attachments:**
- [npe-war-assebmbly.zip](https://issues.apache.org/jira/secure/attachment/12714341/npe-war-assebmbly.zip) (_46.79 kB_)
- [output.log](https://issues.apache.org/jira/secure/attachment/12714306/output.log) (_308.62 kB_)

**Comment by jira-importer** [comment]
**[Robin Roos](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=robinroos2)** commented

Log output

**Comment by jira-importer** [comment]
**[Robin Roos](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=robinroos2)** commented

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single (default) on project acme-dist: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single failed.
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single failed.
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
... 19 more
Caused by: java.lang.NullPointerException
at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver$DefaultFileInfo.isFile(AssemblyProxyArchiver.java:871)
at org.apache.maven.plugin.assembly.filter.ComponentsXmlArchiverFileFilter.isSelected(ComponentsXmlArchiverFileFilter.java:193)
at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.acceptFile(AssemblyProxyArchiver.java:825)
at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.addFile(AssemblyProxyArchiver.java:476)
at org.apache.maven.plugin.assembly.archive.task.AddArtifactTask.execute(AddArtifactTask.java:212)
at org.apache.maven.plugin.assembly.archive.task.AddDependencySetsTask.addNormalArtifact(AddDependencySetsTask.java:351)
at org.apache.maven.plugin.assembly.archive.task.AddDependencySetsTask.addDependencySet(AddDependencySetsTask.java:186)
at org.apache.maven.plugin.assembly.archive.task.AddDependencySetsTask.execute(AddDependencySetsTask.java:124)
at org.apache.maven.plugin.assembly.archive.phase.DependencySetAssemblyPhase.execute(DependencySetAssemblyPhase.java:76)
at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:183)
at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:436)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
... 20 more

**Comment by jira-importer** [comment]
**[Robin Roos](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=robinroos2)** commented

The corresponding issue raised against Webstart Maven Plugin is MWEBSTART-216.  If the error is caused by that plugin (which appears to be the case) they will benefit from input from the Assembly plugin team to help identify and resolve the problem.

**Comment by jira-importer** [comment]
**[Tony Chemit](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tchemit)** commented

You are just using the **jnlp-inline** mojo which is an aggregator mojo, so does not match with your needs.

Just use instead the **jnlp-single** mojo instead to make your example works.
