### ISSUE TITLE
[MASSEMBLY-671] Cryptic debug warning message needs improvement and/or documentation

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#838]
**[Steve Cohen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scohen@javactivity.org)** opened **[MASSEMBLY-671](https://issues.apache.org/jira/browse/MASSEMBLY-671?redirect=false)** and commented

I have used the assembly plugin both versions 2.4 and 2.2.1.  While the plugin basically works, I have some problems with it, (see MASSEMBLY-670), which I suspect may be related to the following message that shows up when running Maven in debug mode (-X):

```
[DEBUG] All known ContainerDescriptorHandler components: [plexus, metaInf-spring, metaInf-services, file-aggregator]
[DEBUG] Cannot find ArtifactResolver with hint: project-cache-aware
org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.apache.maven.artifact.resolver.ArtifactResolver
  roleHint: project-cache-aware
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:257)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:233)
        at org.apache.maven.shared.repository.DefaultRepositoryAssembler.contextualize(DefaultRepositoryAssembler.java:721)
        at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.contextualize(PlexusLifecycleManager.java:317)
        at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.manageLifecycle(PlexusLifecycleManager.java:292)
        at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:148)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1018)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
        at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
        at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
        at org.sonatype.guice.bean.locators.EntryListAdapter$ValueIterator.next(EntryListAdapter.java:112)
        at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:181)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:436)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
       at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.util.NoSuchElementException
        at java.util.Collections$EmptySet$1.next(Collections.java:2912)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
        ... 43 more
```

This message is singularly unhelpful.  Evidently there is something that the plugin doesn't like about my deployment descriptor, but this message tells me nothing that would help me get to the bottom of what that is.  And despite this message, the plugin goes on to give me essentially what I want for an assembly (with the exception of the problem in MASSEMBLY-670).

Users should have better help here in creating assembly descriptors.  Regardless of what is "wrong" (what unwritten law was violated) with my assembly descriptor, a more informative error message or at least documentation should be available.

I am not alone, here.  Google "Cannot find ArtifactResolver with hint: project-cache-aware" and many hits will be found, most of them unanswered.

---

**Affects:** 2.2.1, 2.4

**Issue Links:**
- [MSHARED-383](https://issues.apache.org/jira/browse/MSHARED-383) Remove annyoing stacktrace that is logged in a non-exceptional case
 (_**"depends upon"**_)

2 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

We really need a small sample project that reproduces this problem; it seems like a bug but it also seems to be ignored !

I don't think we should confuse "unwritten laws" with bugs or code that doesn't work too well :)

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

Make a file set with a directory like:

    <directory>{project.build.directory}/foo</directory>
     <outputDirectory>something</outputDirectory>

you will be rewarded with _no_ specific error message about the nonexistence of {project.build.directory} (note the missing $} and that spew in the log.

**Comment by jira-importer** [comment]
**[Steve Cohen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scohen@javactivity.org)** commented

Is THAT a bug?  Shouldn't the $ be legal (and even required)?
Anyway, thanks for the tip.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

I have created a [sample github project](https://github.com/khmarbaise/massembly/tree/master/massembly-671) with Bensons suggestions.
The question is in this case if a non existings directory should produce a warning or fail. The example just produces an zip which does not contain the given directory `something` as i would expect it. So from my point of view this looks like correct behaviour. If someone has supplementals to the example just fork and send pull request so we have a base on which we can discuss this issue. From my current point of view i can't reproduce a wrong behaviour so i will close the issue. If you have objections please don't hesitate to reopen the issue.

**Comment by jira-importer** [comment]
**[William Ferguson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=william_f_au)** commented

Sent pull request containing a simple modification of the assembly descriptor that shows 671.

**Comment by jira-importer** [comment]
**[William Ferguson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=william_f_au)** commented

NB I would open the issue again if I could, but I don't seem to have that capability

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Root cause has now been fixed in maven-repository-builder

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Fixed in r1639566
