### ISSUE TITLE
[MASSEMBLY-251] NullPointer wehn using scope system in a dependencySet

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#845]
**[J-C Walmetz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=j-c)** opened **[MASSEMBLY-251](https://issues.apache.org/jira/browse/MASSEMBLY-251?redirect=false)** and commented

In my pom file, I have define an depency using the scope system. I try to create a zip with the assembly plugin.

in src.xml, I wrote:
\<dependencySet>
\<outputDirectory/>
\<includes>
\<include>x:y\</include>
\</includes>
\<scope>system\</scope>
\<unpack>true\</unpack>
\</dependencySet>

When I execute mvn assembly:assembly, I have the following exception:
java.lang.NullPointerException
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:92)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:73)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:526)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:234)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:245)
at org.apache.maven.plugin.assembly.archive.task.AddDependencySetsTask.addDependencySet(AddDependencySetsTask.java:109)
at org.apache.maven.plugin.assembly.archive.task.AddDependencySetsTask.execute(AddDependencySetsTask.java:90)
at org.apache.maven.plugin.assembly.archive.phase.DependencySetAssemblyPhase.execute(DependencySetAssemblyPhase.java:54)
at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:98)
at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:278)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:493)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:463)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:224)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:280)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---

**Affects:** 2.2-beta-1

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12714081/pom.xml) (_2.33 kB_)

**Comment by jira-importer** [comment]
**[Petar Tahchiev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paranoiabla)** commented

Hi there,

I tried to reproduce this issue with the pom.xml that I have attached and the assembly descriptor you ave specified, but I had no luck.
I cannot reproduce this issue.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Please reopen with a more complete test project that displays the failing case, if this is still happening. I've tried this with 2.0.7, but don't have a test environment handy that has WinXP with Maven 2.0.7 installed. It may be useful to try this against Maven 2.0.9 and Maven 2.1.0-M1 (which is being voted on now, staged at: http://people.apache.org/~jdcasey/stage/apache-maven/2.1.0-M1/org/apache/maven/apache-maven/2.1.0-M1 ).
