### ISSUE TITLE
[MASSEMBLY-191] IncompatibleClassChangeError thrown when invoking the plugin

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#850]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** opened **[MASSEMBLY-191](https://issues.apache.org/jira/browse/MASSEMBLY-191?redirect=false)** and commented

I have a very basic assembly file that throws the following exception;

```
java.lang.IncompatibleClassChangeError
        at org.apache.maven.plugin.assembly.io.DefaultAssemblyReader.readAssemblies(DefaultAssemblyReader.java:74)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:253)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:475)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:454)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

The assembly is the following

```xml
<assembly>
    <id>bundle</id>
    <formats>
        <format>zip</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>

    <fileSets>
        <fileSet>
            <directory>src/main/ant</directory>
            <outputDirectory></outputDirectory>
            <includes>
                <include>build.xml</include>
            </includes>
        </fileSet>
    </fileSets>
    
    <files>
        <file>
            <source>target/${artifactId}-${version}.jar</source>
            <outputDirectory>runner-lib</outputDirectory>
        </file>
    </files>
</assembly>
```

My profile is as follows

```xml
<profile>
       <id>bundle</id>
       <activation>
           <property>
               <name>performRelease</name>
               <value>true</value>
           </property>
       </activation>
       <build>
           <plugins>
               <plugin>
                   <groupId>org.apache.maven.plugins</groupId>
                   <artifactId>maven-assembly-plugin</artifactId>
                   <version>2.2-SNAPSHOT</version>
                   <configuration>
                       <descriptors>
                           <descriptor>src/assembly/bundle.xml</descriptor>
                       </descriptors>
                   </configuration>
                   <executions>
                       <execution>
                           <id>bundle-samples</id>
                           <phase>package</phase>
                           <goals>
                               <goal>attached</goal>
                           </goals>
                       </execution>
                   </executions>
               </plugin>
           </plugins>
       </build>
   </profile>
```

---

**Affects:** 2.2

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Note that i am able to reproduce that with other assembly descriptors.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

fixed. The issue was plexus-archiver 1.0-alpha-8, which pulled in plexux-component-api (which defines Logger, in addition to plexus-container-default-1.0-alpha-9's version).

I added an exclusion for plexus-component-api to the dependency on plexus-archiver, and all's well again.
