### ISSUE TITLE
[MASSEMBLY-249] Crashing file name that is using special chars

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#856]
**[Endrigo Antonini](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eantonini)** opened **[MASSEMBLY-249](https://issues.apache.org/jira/browse/MASSEMBLY-249?redirect=false)** and commented

I was using this plugin to zip. But when I have a file name that uses special chars, like "ç", it crashs when zipping.

Attached is an example of it.

---

**Affects:** 2.2-beta-1

**Attachments:**
- [example.rar](https://issues.apache.org/jira/secure/attachment/12714100/example.rar) (_2.59 kB_)

**Comment by jira-importer** [comment]
**[Petar Tahchiev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paranoiabla)** commented

Hi Endrigo,

I tried to reporduce your problem, but I failed. It works for me. I guess it was a not so much an Assembly plugin issue, but more a Maven issue.
Anyway it works OK for me now with the following configuration:

C:\example>mvn -version
Maven version: 2.0.9
Java version: 1.5.0_15
OS name: "windows xp" version: "5.1" arch: "x86" Family: "windows"

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

When I run this example, it doesn't crash. Instead, when I try to examine the resulting zip file, I get the following:

```
Betelgeuse:example jdcasey$ jar tf target/test-1.0.zip 
test-1.0/
java.lang.IllegalArgumentException
        at java.util.zip.ZipInputStream.getUTF8String(ZipInputStream.java:290)
        at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:243)
        at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:73)
        at sun.tools.jar.Main.list(Main.java:757)
        at sun.tools.jar.Main.run(Main.java:192)
        at sun.tools.jar.Main.main(Main.java:925)
```
