### ISSUE TITLE
[MASSEMBLY-192] regression in repository assembly

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#859]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[MASSEMBLY-192](https://issues.apache.org/jira/browse/MASSEMBLY-192?redirect=false)** and commented

I get this error in 2.2-beta-1:

[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] org.apache.maven.plugin.assembly.archive.phase.wrappers.GroupVersionAlignmentWrapper
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
java.lang.ClassCastException: org.apache.maven.plugin.assembly.archive.phase.wrappers.GroupVersionAlignmentWrapper
at org.apache.maven.shared.repository.DefaultRepositoryAssembler.createGroupVersionAlignments(DefaultRepositoryAssembler.java:439)
at org.apache.maven.shared.repository.DefaultRepositoryAssembler.buildRemoteRepository(DefaultRepositoryAssembler.java:121)
at org.apache.maven.plugin.assembly.archive.phase.RepositoryAssemblyPhase.execute(RepositoryAssemblyPhase.java:68)
at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:98)
at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:278)

Descriptor:
\<assembly>
\<id>bin\</id>
\<formats>
\<format>tar.gz\</format>
\</formats>
\<repositories>
\<repository>
\<outputDirectory>repository/releases\</outputDirectory>
\<includeMetadata>true\</includeMetadata>
\<groupVersionAlignments>
\<groupVersionAlignment>
\<id>org.apache.maven\</id>
\<version>2.0.5-maestro-${project.version}\</version>
\<excludes>
\<exclude>maven-plugin-surrogate-parent\</exclude>
\<exclude>maven-archetype\</exclude>
\<exclude>maven-archetype-core\</exclude>
\<exclude>maven-archiver\</exclude>
\<exclude>maven-parent\</exclude>
\<exclude>maven-jxr\</exclude>
\<exclude>maven-plugin-tools-java\</exclude>
\<exclude>maven-plugin-tools-beanshell\</exclude>
\<exclude>maven-plugin-tools-api\</exclude>
\<exclude>maven-plugin-tools\</exclude>
\</excludes>
\</groupVersionAlignment>
\</groupVersionAlignments>
\</repository>
\</repositories>
\</assembly>

---

**Affects:** 2.2-beta-1

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

forgot an "implements" clause, it looks like.

Brett, would it be possible for you to simplify your config a bit and produce an integration test (just a project and verify script) that we could put in src/it to guard against this regression in future?
