### ISSUE TITLE
[MASSEMBLY-684] Parallel Execution w Custom Assembly Descriptor Fails

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#902]
**[Chris Rompot](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=crompot)** opened **[MASSEMBLY-684](https://issues.apache.org/jira/browse/MASSEMBLY-684?redirect=false)** and commented

When using a custom assembly descriptor and building in parallel (-T threaded), the error below results. It does not occur when using 1) a pre-defined descriptor in parallel or 2) a custom descriptor in a sequential (non-threaded) build. Attached are the error log, pom.xml, and custom assembly descriptor.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single (make-assembly) on project db-account-ga: Failed to create assembly: Error creating assembly archive src: You must set at least one file. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single (make-assembly) on project db-account-ga: Failed to create assembly: Error creating assembly archive src: You must set at least one file.
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:171)
at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:163)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:139)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:440)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:139)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:909)
at java.lang.Thread.run(Thread.java:662)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly: Error creating assembly archive src: You must set at least one file.
at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:495)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
... 13 more
Caused by: org.apache.maven.plugin.assembly.archive.ArchiveCreationException: Error creating assembly archive src: You must set at least one file.
at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:190)
at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:436)
... 15 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: You must set at least one file.
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:246)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:222)
at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:910)
at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.createArchive(AssemblyProxyArchiver.java:512)
at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:186)
... 16 more

---

**Affects:** 2.4

**Attachments:**
- [maven-assembly-plugin-error.log](https://issues.apache.org/jira/secure/attachment/12714362/maven-assembly-plugin-error.log) (_9.94 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12714191/pom.xml) (_1.83 kB_)
- [src-zip-only-assembly.xml](https://issues.apache.org/jira/secure/attachment/12714381/src-zip-only-assembly.xml) (_874 bytes_)

**Issue Links:**
- [MASSEMBLY-692](https://issues.apache.org/jira/browse/MASSEMBLY-692) Assembly ID is global

3 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Just a suggestions. Please try to rename the id of your assembly descriptor into something like `src-my-own` and retry it.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

I have created an [example project based on your attachments](https://github.com/khmarbaise/massembly/tree/master/massembly-684) by which the error message can't be reproduced. Apart from that the error message gives me a different impression.

```
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly: Error creating assembly archive src: You must set at least one file.
```

Can you give a full log output and not only excerpts and please and the command you have given to reproduce the failure? If you have an supplemental information / additions etc. may be you can add the to the above example project (pull-requests?) or put them into this ticket so i can enhance the example accordingly to nail down the problem.

**Comment by jira-importer** [comment]
**[Chris Rompot](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=crompot)** commented

I struggled with github, but have created a simple mutli-module project at https://github.com/crompot/multimodule using your files from https://github.com/khmarbaise/massembly/tree/master/massembly-684.  At the root level, "mvn clean install" always works.  However, "mvn -T 2C clean install" fails frequently in different children modules.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Unfortunately i can acknowledge this behaviour.

**Comment by jira-importer** [comment]
**[Christer Engde](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christer.engde)** commented

I have the same problem:

"mvn clean install" works everytime!

"mvn -T 1.5C clean install" fails sometimes. Rerun may solve it the first time, but it happens everyday that 5 retries isn't enough.

**Comment by jira-importer** [comment]
**[Christer Engde](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christer.engde)** commented

I have modified all assembly xml files now.

Files: \<artifact>/assembly-\<type>.xml
Change: id changed from '\<type>' to '\<artifact>_\<type>'

Builds are running ....
