### ISSUE TITLE
[MASSEMBLY-696] Internal Regexp Error with Windows Paths

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#911]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** opened **[MASSEMBLY-696](https://issues.apache.org/jira/browse/MASSEMBLY-696?redirect=false)** and commented

On windows the Assembly plugin shows this error:

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5-SNAPSHOT:single (default-cli) on project myproject: Execution default-cli of goal org.apache.maven.plugins:maven-assembly-plugin:2.5-SNAPSHOT:single failed: Unexpected internal error near index 1
\
 ^
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
....
Caused by: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
        at java.util.regex.Pattern.error(Pattern.java:1924)
        at java.util.regex.Pattern.compile(Pattern.java:1671)
        at java.util.regex.Pattern.<init>(Pattern.java:1337)
        at java.util.regex.Pattern.compile(Pattern.java:1022)
        at java.lang.String.split(String.java:2313)
        at java.lang.String.split(String.java:2355)
        at org.apache.maven.plugin.assembly.utils.AssemblyFormatUtils.fixRelativeRefs(AssemblyFormatUtils.java:509)

```

---

**Affects:** 2.5

**Attachments:**
- [MASSEMBLY-696.patch](https://issues.apache.org/jira/secure/attachment/12714391/MASSEMBLY-696.patch) (_1.75 kB_)
- [MASSEMBLY-696.tar.gz](https://issues.apache.org/jira/secure/attachment/12714404/MASSEMBLY-696.tar.gz) (_974 bytes_)

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

First thanks for your issue, but can you please define a [SHA1 sum](https://github.com/apache/maven-plugins/commits/trunk) or [SVN revision number](http://svn.apache.org/repos/asf/maven/plugins/trunk/) which can be found in one of those locations which i currently can't...

Furthermore can you give a complete use case for that issue. Fortunately you have created a patch with an appropriate unit test. You have added log output with failures which is very good, but it would be better having a complete use case which can be integrated as an integration test as well..and of course gives other committers the chance to verify this behaviour. BTW. Have you checked this with the last release of maven-assembly-plugin (2.4) instead of 2.5-SNAPSHOT ?

**Comment by jira-importer** [comment]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** commented

Certainly, the SVN revision number is 'trunk'; it occurs since all earlier versions since John added the code:

> 1653fb20 :(John Dennis Casey  2011-02-23 22:05:06 +0000 509)                 parts.addAll( Arrays.asList( value.split( sep ) ) );

I'm working on minifying my project to get you a usecase for an integration test. I think it's due to using ```
${java.home}/lib/tools.jar

```as a system dep somewhere. But the use of _any_ windows paths will trigger this bug.

However the code is simply wrong and shouldn't take a usecase to fix. Simply run this code: 

```

"foo".split( "\\" );

```

; see the Javadoc on Regular Expressions for more info ;-)

Thanks, merry easter!
```

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Hi Kenney, I'm sorry but trunk is no SVN revision number apart from that why are you referencing such an extreme old code...2011 ? The last changes on trunk have been made with revision 1585621...If you could provide an integration test for it it would be great so i can integrate that into the code base.
Thanks in advance.
Happy Easter as well.

**Comment by jira-importer** [comment]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** commented

I'm referencing old code because the bug has been in there that long.

I don't understand your question. What do you need the revision for?  And what revision exactly?

The patch will work against any revision after 1073964, when that line of code was introduced (svn blame/praise/annotate/ann). -And `trunk` is a symbolic name referencing the latest revision in any subversion repository- my bad, I should have said `HEAD` (1588817 at the time of this writing); I was being sarcastic, my apologies, this doesn't always come across on digital media!

Also, it's really not necessary to make an integration test for this one. It's the _unit_ tests for that code that are incomplete as they only check Unix style pathnames, while the code explicitly attempts to deal with windows style paths aswell.

In any case, I've concocted an integration test as per your request.

It took me quite a while to figure out what exactly triggers this code. It occurs when specifying `<unpack>true</unpack>` dependencies and either specifying a non-default value for `<lineEnding/>` or `<filtered/>`. I added some debug to the assembly plugin, and it breaks when `fixRelativeRefs` is called with `.\log4j-1.2.17.jar/`. That this doesn't happen more often is because most code calling `fixRelativeRefs` duplicates code from that method (i.e. stripping `./`, `../` etc).

**Comment by jira-importer** [comment]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** commented

tar xvfz MASSEMBLY-696.tar.gz && cd MASSEMBLY-696 && mvn package

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

patch applied in [r1589280](http://svn.apache.org/r1589280)
Thanks for the patch.

**Comment by jira-importer** [comment]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** commented

Awesome, thank you!
