### ISSUE TITLE
[MASSEMBLY-774] too many open files

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#978]
**[Dan Armbrust](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=armbrust)** opened **[MASSEMBLY-774](https://issues.apache.org/jira/browse/MASSEMBLY-774?redirect=false)** and commented

I ran across this - http://mail-archives.apache.org/mod_mbox/maven-dev/201501.mbox/%3CA2EE0D04-04E3-4C99-8842-67346386200C@takari.io%3E - and since I'm making huge zip files, I thought I would give it a try.

I configured as:

    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>2.5.5</version>
        <dependencies>
            <dependency>
                <groupId>org.codehaus.plexus</groupId>
                <artifactId>plexus-archiver</artifactId>
                <version>3.0.1</version>
            </dependency>
            <dependency>
                <groupId>org.codehaus.plexus</groupId>
                <artifactId>plexus-io</artifactId>
                <version>2.6</version>
            </dependency>
        </dependencies>
    </plugin>

But this lead to a failure:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (zip) on project ... sememe/seg.3182.sememe.map (Too many open files) -> [Help 1]

I certainly could raise my ulimit:

darmbrust@overkill:/mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods$ ulimit -a
...
open files                      (-n) 1024

But it seems it would be better if the zip process limited itself to a reasonable number of open files.  I don't know the algorithm... but it seems that double or triple the processor count would be more than enough.

---

**Affects:** 2.5.5

**Remote Links:**
- [plexus-archiver issue
](https://github.com/codehaus-plexus/plexus-archiver/issues/6)

4 votes, 10 watchers

**Comment by jira-importer** [comment]
**[Dan Armbrust](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=armbrust)** commented

As a side note, the performance of the multi-threaded zip is a nice improvement - one of our build cycles went from 22 minutes to 16 with this change.

But I can't use it until it will work without mucking with file limits on linux.

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Can you run with mvn -e and include the stacktrace of where the file allocation is failing ?
(Maybe run a few times to see if it fails in the same place, include all stack traces if different)

(This was fixed in https://github.com/codehaus-plexus/plexus-archiver/issues/6, but there appears to be multiple code paths with this problem then..)

**Comment by jira-importer** [comment]
**[Dan Armbrust](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=armbrust)** commented

Sure - here are some details:

```
[DEBUG] All known ContainerDescriptorHandler components: [plexus, metaInf-services, metaInf-spring, file-aggregator]
[DEBUG] No ArtifactResolver with hint project-cache-aware
[DEBUG] FileSet[object-chronicles/] dir perms: -1 file perms: -1
[DEBUG] The archive base directory is 'null'
[DEBUG] NOT reformatting any files in /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles
[DEBUG] Adding file-set in: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles to archive location: snomed-1.10-SNAPSHOT-all.data/object-chronicles/
[DEBUG] FileSet[META-INF/] dir perms: -1 file perms: -1
[DEBUG] The archive base directory is 'null'
[DEBUG] NOT reformatting any files in /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/META-INF
[DEBUG] Adding file-set in: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/META-INF to archive location: snomed-1.10-SNAPSHOT-all.data/META-INF/
[INFO] Building zip: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.cradle.zip

--snip--

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (zip) on project snomed: Failed to create assembly: Error creating assembly archive all.cradle: Problem creating zip: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles/cradle/sememe/seg.2168.sememe.map (Too many open files) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (zip) on project snomed: Failed to create assembly: Error creating assembly archive all.cradle: Problem creating zip: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles/cradle/sememe/seg.2168.sememe.map (Too many open files)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly: Error creating assembly archive all.cradle: Problem creating zip: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles/cradle/sememe/seg.2168.sememe.map (Too many open files)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:541)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.apache.maven.plugin.assembly.archive.ArchiveCreationException: Error creating assembly archive all.cradle: Problem creating zip: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles/cradle/sememe/seg.2168.sememe.map (Too many open files)
        at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:185)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:484)
        ... 21 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: Problem creating zip: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles/cradle/sememe/seg.2168.sememe.map (Too many open files)
        at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:933)
        at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.createArchive(AssemblyProxyArchiver.java:437)
        at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:181)
        ... 22 more
Caused by: java.io.FileNotFoundException: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles/cradle/sememe/seg.2168.sememe.map (Too many open files)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.codehaus.plexus.components.io.resources.PlexusIoFileResource$1.getContents(PlexusIoFileResource.java:99)
        at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.getContents(PlexusIoFileResource.java:124)
        at org.codehaus.plexus.archiver.ArchiveEntry.getInputStream(ArchiveEntry.java:126)
        at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.zipFile(AbstractZipArchiver.java:492)
        at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.addResources(AbstractZipArchiver.java:365)
        at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:321)
        at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:222)
        at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:916)
        ... 24 more
```

Will run a couple more times, and see if the stack line numbers are the same.

**Comment by jira-importer** [comment]
**[Dan Armbrust](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=armbrust)** commented

Looks consistent:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (zip) on project snomed: Failed to create assembly: Error creating assembly archive all.cradle: Problem creating zip: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles/cradle/sememe/seg.1990.sememe.map (Too many open files) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (zip) on project snomed: Failed to create assembly: Error creating assembly archive all.cradle: Problem creating zip: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles/cradle/sememe/seg.1990.sememe.map (Too many open files)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly: Error creating assembly archive all.cradle: Problem creating zip: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles/cradle/sememe/seg.1990.sememe.map (Too many open files)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:541)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.apache.maven.plugin.assembly.archive.ArchiveCreationException: Error creating assembly archive all.cradle: Problem creating zip: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles/cradle/sememe/seg.1990.sememe.map (Too many open files)
        at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:185)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:484)
        ... 21 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: Problem creating zip: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles/cradle/sememe/seg.1990.sememe.map (Too many open files)
        at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:933)
        at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.createArchive(AssemblyProxyArchiver.java:437)
        at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:181)
        ... 22 more
Caused by: java.io.FileNotFoundException: /mnt/STORAGE/Work/Apelon/Workspaces/ISAAC-Core-2/va-solor-goods/snomed/target/snomed-1.10-SNAPSHOT-all.data/object-chronicles/cradle/sememe/seg.1990.sememe.map (Too many open files)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.codehaus.plexus.components.io.resources.PlexusIoFileResource$1.getContents(PlexusIoFileResource.java:99)
        at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.getContents(PlexusIoFileResource.java:124)
        at org.codehaus.plexus.archiver.ArchiveEntry.getInputStream(ArchiveEntry.java:126)
        at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.zipFile(AbstractZipArchiver.java:492)
        at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.addResources(AbstractZipArchiver.java:365)
        at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:321)
        at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:222)
        at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:916)
        ... 24 more

```

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

It would appear I fixed this on the 2.x branch **after** releasing 3.0.1. If you switch to version 2.10.3 it should work fine. Once you confirm this I'll release 3.0.2

**Comment by jira-importer** [comment]
**[Dan Armbrust](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=armbrust)** commented

Yes - it looks good on 2.10.3.  Thanks!

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

The only versions which exists can be found in Maven Central: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.apache.maven.plugins%22%20AND%20a%3A%22maven-assembly-plugin%22

There does not exist a version 2.10.3 of maven-assembly-plugin...

**Comment by jira-importer** [comment]
**[Elliotte Rusty Harold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elharo)** commented

Is this fixed at head?

**Comment by jira-importer** [comment]
**[Geoff Soutter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gsoutter)** commented

OK, love being wrong, so with sample size of 1, an upgrade to 3.1 and my CI build worked. So it _maybe_ fixed. YMMV.
