### ISSUE TITLE
[MASSEMBLY-766] OOM with 1CPU

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-assembly-plugin#982]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** opened **[MASSEMBLY-766](https://issues.apache.org/jira/browse/MASSEMBLY-766?redirect=false)** and commented

Just happen to run on 1CPU VM, and VM crash on OOM

sample errors

# 

1. There is insufficient memory for the Java Runtime Environment to continue.
2. Native memory allocation (malloc) failed to allocate 82576 bytes for Chunk::new
3. An error report file with more information is saved as:
4. /var/lib/jenkins/jobs/xxxx-all-bugId-template/workspace/hs_err_pid26261.log

# 

1. Compiler replay data is saved as:
2. /var/lib/jenkins/jobs/xxx-all-bugId-template/workspace/replay_pid26261.log
   Build step 'Invoke top-level Maven targets' marked build as failure

another one

[INFO] --- maven-assembly-plugin:2.5.4:single (uber-jar) @ xxx-configmgr ---
mmap failed for CEN and END part of zip file

java.lang.OutOfMemoryError
at java.util.zip.ZipFile.open(Native Method)
....
org.codehaus.plexus.archiver.zip.PlexusIoZipFileResourceCollection$1.getResource(PlexusIoZipFileResourceCollection.java:69)
at org.codehaus.plexus.archiver.zip.PlexusIoZipFileResourceCollection$ZipFileResourceIterator$1.getURL(PlexusIoZipFileResourceCollection.java:125)
at org.codehaus.plexus.components.io.resources.PlexusIoURLResource.getContents(PlexusIoURLResource.java:37)
at ....
org.codehaus.plexus.archiver.ArchiveEntry.getInputStream(ArchiveEntry.java:126)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.zipFile(AbstractZipArchiver.java:514)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.addResources(AbstractZipArchiver.java:370)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:326)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:227)
at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:990)
at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.createArchive(AssemblyProxyArchiver.java:437)
at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:181)
at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:484)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

---

**Affects:** 2.5.4

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Sorry, I read the code all wrong in my initial response.

The current code is aligned for using 10mb per cpu core before offloading to disk. So if you CPU has 8 cores + 8 ht you're looking at 160mb increased memory usage. All of this is an increase when compared with 2.5.3. Would this seem to fit for your case ? (I.e. does increasin -Xmx with 150-ish megs solve the problem ?)

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

Increasing heap memory does not fix the issue

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Exactly how large are your assemblies and how many cores does your CPU report ? (cat /proc/cpuinfo)

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

my build has about 10+ fat jars built by maven-assembly-plugin vary from 30M to 130M. at the time of this issue, I have only 1 CPU.  Unfortunately, I nolonger have that VM

I have my max heap set on 1G to 2G. Current IT folk increase the CPU to 6 and it has 2 core. of course i dont see OOM any more

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

I am not entirely sure I understand this issue. You seemingly OOM'ed on a single cpu core, but it works fine with a bunch of cores ? Or did just too many things change when the problem went away ? My initial reaction was that this was a concurrency problem, but there may be a different explanation:

The semantics of unpacking zip files for including into other archives also changed; we tend to keep the underlying "source" zip files open for a longer time on 2.5.4 than we did on 2.5.3, this may have adverse effects on memory consumption when (for instance) unpacking a large number of zip/jar files into a larger file. From the stack trace you're supplying it actually may look like that's the case.

The simplest way to actually find the problem would be to diff a profiler run with 2.5.3 vs 2.5.4; any chance you could try that ?

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

yes, It works on a bunch of cores.

ATM, don't have any cycle to do profiler diff, not promise when I can try

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

Let's close this ticket since it is no longer practical
